### ISSUE TITLE
Building dm requires running mysqld

### ISSUE THREAD

**Issue by kolbe** [pingcap/dm#105]
It looks like simply building dm requires a running mysqld for some reason. Maybe for a test suite, maybe for something else? It seems like this should not be a requirement simply for a build... or at minimum it ought to be better documented.

Is the solution as easy as removing "`test`" from the "`build`" target in Makefile?

**Comment by amyangfei** [comment]
thanks @kolbe 
we have removed `test` from `build` target in Makefile, so close this issue now
