### ISSUE TITLE
stop/pause until reached the end of a transaction

### ISSUE THREAD

**Issue by csuzhangxc** [pingcap/dm#1095]
## Feature Request

**Is your feature request related to a problem? Please describe:**

DM split transactions from upstream MySQL into rows and re-aggregate rows into a new transaction as a batch.

When `stop-task` or `pause-task`, maybe only a part of rows in an upstream MySQL transaction have been committed into the downstream TiDB, in other words, the original transaction is broken in TiDB after that.

**Describe the feature you'd like:**

stop/pause the task until reached the end of a transaction for `start-task`/`pause-task` or shutdown the DM-worker process normally.

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by lance6716** [comment]
another way is revert to last consistent point (maybe recorded in checkpoint) if TiDB could flashback table

https://github.com/pingcap/tidb/issues/20302

**Comment by lichunzhu** [comment]
Maybe we can refer to tidb-binlog's logic:
1. Don't send any sqls later than the current transation.
2. Close syncer until all sqls are replicated to downstream.
3. Add a boolean column `synced` in downstream checkpoint to notify whether DM really stops at a certain transaction.

https://github.com/pingcap/tidb-binlog/blob/v4.0.13/drainer/syncer.go#L484

**Comment by okJiang** [comment]
How about saving to the end of the transaction(xid event) directly every time `saveTablePoint`?

**Comment by okJiang** [comment]
> How about saving to the end of the transaction(last xid event) directly every time `saveTablePoint`?

Since this cannot guarantee the consistency of upstream and downstream data, we choose to delay syncer when stop/pause until the end of the transaction, and then `flushCheckPoint`.

**Comment by okJiang** [comment]
Initial idea: Delay when syncer exits and job closes. https://github.com/pingcap/dm/blob/11fb5a8b63200efa2d6bbb2fa3bcb36d90e4f575/syncer/syncer.go#L3040

- Wait for the arrival of XIDEvent before closing the job channel.

Steps:

1. Before closing the job channel, set `Syncer.waitXIDType = waiting`. Then wait `Syncer.waitXIDType = waitComplete` here.
2. After setting `Syncer.waitXIDType = waiting`, `Syncer` is running normaly until `addJob` encounter a `XIDEvent`.
3. After encountering a `XIDEvent`, 
    a. set `Syncer.waitXIDType = waitComplete`
    b. stop `addJob`
    c. continue close `jobChan` in 1
4. The job in jobQueue is continue to be executed here. (by add `executeSQLs()`) https://github.com/pingcap/dm/blob/11fb5a8b63200efa2d6bbb2fa3bcb36d90e4f575/syncer/syncer.go#L1322-L1326


PTAL @lance6716 @lichunzhu

**Comment by lance6716** [comment]
there're so many states of syncer: normal replication, sharing re-sync, handle-error injected some SQL, check whether to turn off safe mode, and your waiting xid.

could you use a more clear way to express above states and their transition? maybe a state machine

**Comment by okJiang** [comment]
> there're so many states of syncer: normal replication, sharing re-sync, handle-error injected some SQL, check whether to turn off safe mode, and your waiting xid.
> 
> could you use a more clear way to express above states and their transition? maybe a state machine

I'm afraid I can't fully understand all the above states in a short time
