### ISSUE TITLE
Can't track "create table t1 like t2"

### ISSUE THREAD

**Issue by csuzhangxc** [pingcap/dm#1099]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

2. What did you expect to see?

3. What did you see instead?

    
![image](https://user-images.githubusercontent.com/3183039/94218860-ffd98e80-ff17-11ea-84bf-e2a365135a55.png)

4. Versions of the cluster

    - DM version (run `dmctl -V` or `dm-worker -V` or `dm-master -V`):

        ```
        v2.0.0-rc.2
        ```

**Comment by lance6716** [comment]
`ALTER` https://dev.mysql.com/doc/refman/5.7/en/alter-table.html#alter-table-foreign-key
- `ADD CONSTRAINT name FOREIGN KEY`

`CREATE TABLE` https://dev.mysql.com/doc/refman/5.7/en/create-table.html#create-table-clone-copy https://dev.mysql.com/doc/refman/5.7/en/create-table.html#create-table-indexes-keys
- `LIKE`
- `[AS] query_expression` (GTID mode disable this)
- `FOREIGN KEY` (TiDB ignore this)

`CREATE VIEW` https://dev.mysql.com/doc/refman/5.7/en/create-view.html
- `AS`
