### ISSUE TITLE
worker offline after kill master

### ISSUE THREAD

**Issue by GMHDBJD** [pingcap/dm#1110]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.
start multiple masters
join worker with one master
kill that master
run `list-member --worker`
2. What did you expect to see?
worker online
3. What did you see instead?
```
"workers": [
                    {
                        "name": "worker2",
                        "addr": "127.0.0.1:8263",
                        "stage": "offline",
                        "source": ""
                    }
                ]
```
4. Versions of the cluster

    - DM version (run `dmctl -V` or `dm-worker -V` or `dm-master -V`):

        ```
        master
        ```
5 root cause
worker [keepalive](https://github.com/pingcap/dm/blob/aef0f37df67a7a49d49fed1bb555042606c80436/dm/worker/join.go#L98) with join url only

**Comment by lance6716** [comment]
After fixing this issue, we should change upgraing master action in `run-compatibility-test` from kill-and-replace to join-and-kill-old

https://github.com/pingcap/dm/pull/1128
