### ISSUE TITLE
"concurrent map read and map write" for loader checkpoint

### ISSUE THREAD

**Issue by csuzhangxc** [pingcap/dm#1143]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

2. What did you expect to see?

3. What did you see instead?

4. Versions of the cluster

    - DM version (run `dmctl -V` or `dm-worker -V` or `dm-master -V`):

        ```
        DM master until https://github.com/pingcap/dm/commit/0ca7f5424d5bdd877d99b95d5824f08e68ddba0b
        ```

[dm-worker-2_default_dm-worker-97ea66f4c3f18b498b71eb9299d8223c00c8bf6cf4d3f4396691cec79fa6a089.log](https://github.com/pingcap/dm/files/5363382/dm-worker-2_default_dm-worker-97ea66f4c3f18b498b71eb9299d8223c00c8bf6cf4d3f4396691cec79fa6a089.log)

**Comment by lance6716** [comment]
didn't find in uploaded log 🤔

**Comment by csuzhangxc** [comment]
> didn't find in uploaded log 🤔

@lance6716 updated, I updated another wrong log previously.
