### ISSUE TITLE
pingcap/dm:v1.0.6 (and probably others) docker image fails DNS resolution with 'mydumper'

### ISSUE THREAD

**Issue by agaffney** [pingcap/dm#1149]
## Bug Report

When using the `pingcap/dm:v1.0.6` docker image, I was unable to configure syncing due to the `mydumper` binary throwing errors about being unable to resolve DNS names. This appears to be due to the image being based on Alpine Linux. When I built my own custom image based on Ubuntu using the exact same binary, DNS resolution worked fine in `mydumper`.

This can be reproduced with a very simple test:

```
$ docker run -ti --rm pingcap/dm:v1.0.6 /mydumper --host google.com

** (mydumper:1): CRITICAL **: 13:35:42.857: failed to resolve host google.com
```

**Comment by lance6716** [comment]
thanks, will fix this problem soon

**Comment by lance6716** [comment]
Seems mydumper doesn't fit well with alpine. I tested our [dumpling](https://github.com/pingcap/dumpling), it could work in this container. Since mydumper will be no longer needed in DM v2.0, we would not change base OS image to keep it small. Sorry for the inconvenience.
