### ISSUE TITLE
启动任务式报错

### ISSUE THREAD

**Issue by chengshihard** [pingcap/dm#1245]
![image](https://user-images.githubusercontent.com/13564095/97652436-4d0dca80-1a99-11eb-8532-61a570862e6f.png)

这个是什么原因 求帮助

**Comment by csuzhangxc** [comment]
you need more DM-worker instances to handle sources. see https://docs.pingcap.com/zh/tidb-data-migration/v2.0/overview#%E9%AB%98%E5%8F%AF%E7%94%A8.

or you can ask questions in https://asktug.com/.
