### ISSUE TITLE
`handle-error` didn't return error when it can't revert

### ISSUE THREAD

**Issue by GMHDBJD** [pingcap/dm#1249]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.
```
handle-error task skip -b pos
# task running, event at `pos` was skipped, checkpoint havn't been flushed to downstream
handle-error task revert -b pos
```
2. What did you expect to see?
```
{
    "result": true,
    "msg": "",
    "sources": [
        {
            "result": false,
            "msg": "operator .* no exist",
            "source": "mysql-replica-01",
            "worker": "worker1"
        }
    ]
}
```
3. What did you see instead?
```
{
    "result": true,
    "msg": "",
    "sources": [
        {
            "result": true,
            "msg": "",
            "source": "mysql-replica-01",
            "worker": "worker1"
        }
    ]
}
```
4. Versions of the cluster

    - DM version (run `dmctl -V` or `dm-worker -V` or `dm-master -V`):

        ```
        master
        ```

**Comment by okJiang** [comment]
`FlushCheckPoint` after `skip` and `replace` everytime maybe exist the following problems:

1. For non-handle-error `skip` operations, `flush` will also be executed, which affects performance.
2. Where to confirm accurately the completion of `replace` is also a problem.

question:

- Can we use `GlobalPoint()` instead of `FlushedGlobalPoint()` in https://github.com/pingcap/dm/blob/master/syncer/handle_error.go#L62? 
- If yes, we can add a `xid` event in the end when skipped or replaced, that represents `skip` and `replace` is over.

**Comment by okJiang** [comment]
> `FlushCheckPoint` after `skip` and `replace` everytime maybe exist the following problems:
> 
> 1. For non-handle-error `skip` operations, `flush` will also be executed, which affects performance.
> 2. Where to confirm accurately the completion of `replace` is also a problem.
> 
> question:
> 
> * Can we use `GlobalPoint()` instead of `FlushedGlobalPoint()` in [https://github.com/pingcap/dm/blob/master/syncer/handle_error.go#L62](https://github.com/pingcap/dm/blob/master/syncer/handle_error.go?rgh-link-date=2021-08-05T09%3A31%3A59Z#L62)?
> * If yes, we can add a `xid` event in the end when skipped or replaced, that represents `skip` and `replace` is over.

Consider may replace one event in a transaction, it is not a good solution to add `xid` event.

**Comment by GMHDBJD** [comment]
> Consider may replace one event in a transaction, it is not a good solution to add `xid` event.

Now we only support skip/replace DDL. MySQL doesn't support ddl in transaction. So I think it's not a problem.

**Comment by GMHDBJD** [comment]
> For non-handle-error skip operations, flush will also be executed, which affects performance.

What's the meaning of non-handle-error skip operations?

**Comment by okJiang** [comment]
> > For non-handle-error skip operations, flush will also be executed, which affects performance.
> 
> What's the meaning of non-handle-error skip operations?

I thought it is to flush after the skip event. And there are many other situations for skip event.

**Comment by okJiang** [comment]
> > Consider may replace one event in a transaction, it is not a good solution to add `xid` event.
> 
> Now we only support skip/replace DDL. MySQL doesn't support ddl in transaction. So I think it's not a problem.

Is it possible that we will support skip/replace of dml in the future?

**Comment by GMHDBJD** [comment]
> I thought it is to flush after the `addJob`'s skip event. And there are many other situations for it.

No. It is to flush after the manually skip operation. The logic is [here](https://github.com/pingcap/dm/blob/b3a6fd17d6c81aadca48b0d5a90b366e56ccfa49/syncer/syncer.go#L1793)
