### ISSUE TITLE
Lack create database for table route

### ISSUE THREAD

**Issue by jiyfhust** [pingcap/dm#1286]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

step1:  create a database jiyf in mysql.
            create table jiyf.a1, jiyf.a2

step2:  start a task with table route, like this:

routes:
  instance-store-rule-1:
    schema-pattern: "jiyf"
    table-pattern: "a1"
    target-schema: "jiyf11"
    target-table:  "a1"
  instance-store-rule-2:
    schema-pattern: "jiyf"
    table-pattern: "a2"
    target-schema: "jiyf22"
    target-table: "a2"

step3: start the task, error occured. 

USE `jiyf11`; RawCause": "Error 1049: Unknown database 'jiyf11'",

2. What did you expect to see?

3. What did you see instead?

4. Versions of the cluster

    - DM version (run `dmctl -V` or `dm-worker -V` or `dm-master -V`):

        ```
        Release Version: v2.0.0
Git Commit Hash: e6ca256257fbe6e744892841537a16eb84469116
Git Branch: release-2.0
UTC Build Time: 2020-10-30 07:44:03
Go Version: go version go1.13 linux/amd64
        ```

    - Upstream MySQL/MariaDB server version:

        ```
        (paste upstream MySQL/MariaDB server version here)
        ```

    - Downstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

        ```
        (paste TiDB cluster version here)
        ```

    - How did you deploy DM: DM-Ansible or manually?

        ```
        (leave DM-Ansible or manually here)
        ```

    - Other interesting information (system version, hardware config, etc):

        >
        >

5. current status of DM cluster (execute `query-status` in dmctl)

6. Operation logs
   - Please upload `dm-worker.log` for every DM-worker instance if possible
   - Please upload `dm-master.log` if possible
   - Other interesting logs
   - Output of dmctl's commands with problems
   
7. Configuration of the cluster and the task
   - `dm-worker.toml` for every DM-worker instance if possible
   - `dm-master.toml` for DM-master if possible
   - task config, like `task.yaml` if possible
   - `inventory.ini` if deployed by DM-Ansible

8. Screenshot/exported-PDF of Grafana dashboard or metrics' graph in Prometheus for DM if possible

when dm-worker create database to downstream, it lack create database for table routing.
In the case, it forget to create database jiyf11 and jiyf12.

https://github.com/pingcap/dm/blob/6dc77035b3243d15d9bc7307b814b55df52f761c/loader/loader.go#L1120

 renameShardingSchema is needed before renameShardingTable.

**Comment by jiyfhust** [comment]
Hi，is it a result as desired? If not, are you  going to fix it？

**Comment by csuzhangxc** [comment]
> The match rule of schema needs to be configured separately, which is used to migrate CREATE/DROP SCHEMA xx, as shown in rule-2 of the parameter configuration.

you need another route-rule for schema-level operations, see https://docs.pingcap.com/tidb-data-migration/stable/key-features#table-routing

**Comment by jiyfhust** [comment]
I do not think schema-level route-rule can solve it. In my case，table datas from same upstream schema are routed to tables in differrent schemas. A schema-level route-rule can not match more than one destination schemas.

routes:
instance-store-rule-1:
schema-pattern: "jiyf"
table-pattern: "a1"
target-schema: "jiyf11"
target-table: "a1"
instance-store-rule-2:
schema-pattern: "jiyf"
table-pattern: "a2"
target-schema: "jiyf22"
target-table: "a2"

jiyf->jiyf11 and jiyf->jiyf22，how can schema rule match the case?

**Comment by csuzhangxc** [comment]
I think there are two options for your case:

1. split route-rules into two data migration tasks, one for `jiyf.a1` and another for `jiyf.a2`
2. `CREATE DATABASE` in the downstream manually

**Comment by jiyfhust** [comment]
I think the above two idea can all solve it and I prefer the second at present. But I also think code can solve it better. Expect dm be more usable and perfect.

**Comment by csuzhangxc** [comment]
> I think the above two idea can all solve it and I prefer the second at present. But I also think code can solve it better. Expect dm be more usable and perfect.

YES, That should be better if the code can solve it.

but we should clarify the behavior first.

for your cases, you mean?

- only use current table-level route-routes
- and create both `jiyf11` and `jiyf22` for upstream `CREATE DATABASE jiyf` (or if we need drop both schemas for `DROP DATABASE`?) or always create a database if it does not exist?

**Comment by jiyfhust** [comment]
I mean. DM will create database，in the case it created "jiyf", and a error message occurred , it is the smallest case for the question. 
I am not sure how to solve drop database case, i think it is a complex problem with complex cases, as the route rule, it may route to a schema, or the default "same schema",  but hard to find "jiyf11" or "jiyf22" unless a schema route defined.

**Comment by lance6716** [comment]
@jiyfhust could you help us to investigate side-effects of CREATE DATABASE? In other words, if DM auto create database for "no database" error, will it introduce more problems?

**Comment by jiyfhust** [comment]
@lance6716 I'm sorry for forgetting to read this message.  I think there is no perfect method for all cases. In fact DM try to create database for schema level route, but just so it may not satisfy cases like the example.   For the case，I can create the db needed myself to solve it，and the result is the db also created. I think there should separate from drop database，because drop itself need  much disscussion.

**Comment by lance6716** [comment]
> @lance6716 I'm sorry for forgetting to read this message. I think there is no perfect method for all cases. In fact DM try to create database for schema level route, but just so it may not satisfy cases like the example. For the case，I can create the db needed myself to solve it，and the result is the db also created. I think there should separate from drop database，because drop itself need much disscussion.

could you join https://slack.tidb.io/invite?team=tidb-community&channel=sig-migrate&ref=github_sig and give better explanation of you suggestion 😂

**Comment by jiyfhust** [comment]
> > @lance6716 I'm sorry for forgetting to read this message. I think there is no perfect method for all cases. In fact DM try to create database for schema level route, but just so it may not satisfy cases like the example. For the case，I can create the db needed myself to solve it，and the result is the db also created. I think there should separate from drop database，because drop itself need much disscussion.
> 
> could you join https://slack.tidb.io/invite?team=tidb-community&channel=sig-migrate&ref=github_sig and give better explanation of you suggestion 😂

Done. This is not a big problem, maybe just a choice. It is okay if designed this way.

**Comment by lance6716** [comment]
> > > @lance6716 I'm sorry for forgetting to read this message. I think there is no perfect method for all cases. In fact DM try to create database for schema level route, but just so it may not satisfy cases like the example. For the case，I can create the db needed myself to solve it，and the result is the db also created. I think there should separate from drop database，because drop itself need much disscussion.
> > 
> > 
> > could you join https://slack.tidb.io/invite?team=tidb-community&channel=sig-migrate&ref=github_sig and give better explanation of you suggestion 😂
> 
> Done. This is not a big problem, maybe just a choice. It is okay if designed this way.

didn't find you in Slack. are you in sig-migrate or other channel?

**Comment by jiyfhust** [comment]
> didn't find you in Slack. are you in sig-migrate or other channel?

I just joined sig-migrate😂, my id: jiyf.
