### ISSUE TITLE
Didn't fully support sync view while remove view from builtin skip DDLs

### ISSUE THREAD

**Issue by lance6716** [pingcap/dm#1300]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

create view in upstream

2. What did you expect to see?

3. What did you see instead?

error 11007 unknown type DDL

4. Versions of the cluster

    - DM version (run `dmctl -V` or `dm-worker -V` or `dm-master -V`):

        master

**Comment by lance6716** [comment]
in https://github.com/pingcap/dm/pull/1105 we allow syncing of CREATE VIEW, but didn't add an integration test (unit test didn't expose the problem, which maybe SplitDDL can't handle VIEW)

**Comment by lance6716** [comment]
since we didn't dump&load view, how about still filter out VIEW in sync 😂

**Comment by csuzhangxc** [comment]
> since we didn't dump&load view, how about still filter out VIEW in sync 😂

or add support for dump&load view?

**Comment by lance6716** [comment]
> > since we didn't dump&load view, how about still filter out VIEW in sync 😂
> 
> or add support for dump&load view?

OK, will learn from https://github.com/pingcap/tidb-lightning/pull/417. I'm not sure this could be finished in coming release 😂

**Comment by lichunzhu** [comment]
Just load views after all the tables have been loaded. Dumpling has already supported dumping views like mydumper https://github.com/pingcap/dumpling/pull/158

**Comment by cyliu0** [comment]
A community user is questioning about dm supporting view yesterday. So this could be a customer issue in some cases.

**Comment by glkappe** [comment]
@lance6716 How is the progress of this issue?

**Comment by lance6716** [comment]
> @lance6716 How is the progress of this issue?

above this comment is a pull request that fixes this issue. if it gets reviewed quickly, this could be supported in nightly this week.

**Comment by lance6716** [comment]
block syncing of VIEW in https://github.com/pingcap/dm/pull/1331 and will support it later. changed to feature-request

**Comment by lance6716** [comment]
repalced by https://github.com/pingcap/dm/issues/1622
