### ISSUE TITLE
RPC framework refine and refactor

### ISSUE THREAD

**Issue by amyangfei** [pingcap/dm#131]
## Feature Request

**Is your feature request related to a problem? Please describe:**

we have some problems in our rpc framework:
1. not friendly to add new API
2. correctness is not well tested, without no unit test
3. stability under high load is not tested.

**Describe the feature you'd like:**

- [x] refactor framework, make it easy to extend [dm#157](https://github.com/pingcap/dm/pull/157)
- [x] add unit test to all API [dm#148](https://github.com/pingcap/dm/pull/148)
- [ ] add load preasure test

**Comment by csuzhangxc** [comment]
we have used etcd as the operation queue between DM-master and DM-worker in DM 2.0.
