### ISSUE TITLE
Add delete-task command

### ISSUE THREAD

**Issue by Win-Man** [pingcap/dm#1318]
## Feature Request

**Is your feature request related to a problem? Please describe:**

I stoped the task through `stop-task` command, and didn't find the task in result of `query-status`. But I could find the task in Prometheus metrics. It makes me puzzled.

**Describe the feature you'd like:**

Add delete-task to operate users to delete tasks and clean up corresponding information.

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by lance6716** [comment]
What about `stop-task` should also clean metrics instead of add new command?

**Comment by Win-Man** [comment]
If user start the task using `start-task` again and find the metrics disappeared, it may also makes user puzzled.

**Comment by lance6716** [comment]
> If user start the task using `start-task` again and find the metrics disappeared, it may also makes user puzzled.

start will create new metric if works well. And `pause-task` could keep metrics as well as `resume-task` continue using that metrics

**Comment by Win-Man** [comment]
Got it, it seems `stop-task` will clean metrics is another solution.
