### ISSUE TITLE
precheck didn't work so dumpling created illegal metadata

### ISSUE THREAD

**Issue by lance6716** [pingcap/dm#1320]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

https://asktug.com/t/topic/64011/7

2. What did you expect to see?

since this error is `Error 1227: Access denied; you need (at least one of) the SUPER, REPLICATION CLIENT privilege(s) for this operation`, missing of REPLICATION CLIENT should be deteced early

3. What did you see instead?

parse mydumper metadata error: EOF, metadata: Started dump at: 2020-12-01 18:16:30\nSHOW MASTER STATUS:\nSHOW MASTER STATUS: /* AFTER CONNECTION POOL ESTABLISHED */\nFinished dump at: 2020-12-01 23:07:35\n

4. Versions of the cluster

    - DM version (run `dmctl -V` or `dm-worker -V` or `dm-master -V`):

        2.0.0

    - Upstream MySQL/MariaDB server version:

        MySQL 8.0.14

    - Downstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

        ```
        (paste TiDB cluster version here)
        ```

    - How did you deploy DM: DM-Ansible or manually?

        ```
        (leave DM-Ansible or manually here)
        ```

    - Other interesting information (system version, hardware config, etc):

        >
        >

5. current status of DM cluster (execute `query-status` in dmctl)

6. Operation logs
   - Please upload `dm-worker.log` for every DM-worker instance if possible
   - Please upload `dm-master.log` if possible
   - Other interesting logs
   - Output of dmctl's commands with problems
   
7. Configuration of the cluster and the task
   - `dm-worker.toml` for every DM-worker instance if possible
   - `dm-master.toml` for DM-master if possible
   - task config, like `task.yaml` if possible
   - `inventory.ini` if deployed by DM-Ansible

8. Screenshot/exported-PDF of Grafana dashboard or metrics' graph in Prometheus for DM if possible

**Comment by glkappe** [comment]
@lance6716 This issue will be cherry picked in which version of dm

**Comment by lance6716** [comment]
> @lance6716 This issue will be cherry picked in which version of dm

the root cause is still not located, maybe it's a MySQL 8.0 problem. If so, DM v1.0 didn't support MySQL 8.0 so that's out of our support

**Comment by lance6716** [comment]
> @lance6716 This issue will be cherry picked in which version of dm

This is not a MySQL 8.0 problem, so it should effect all version of DM. We should check privilege in a finer way, that is checking granted databases/tables. Specifically, `REPLICATION CLIENT` should be granted on `*.*`.

After fixing, lacking privilege should be reported in pre-check
