### ISSUE TITLE
Official document about version restriction

### ISSUE THREAD

**Issue by Carl-Hee** [pingcap/dm#1328]
## Question

The document has the restriction like:

Note:
If there is a primary-secondary migration structure between the upstream MySQL/MariaDB servers, then choose the following version.
5.7.1 < MySQL version < 8.0
MariaDB version >= 10.1.3

I am a bit of confused. Is that means the if upstream use mysql AND mariadb as master-slave structure, then you should adopt the version as mentioned?  In other words, my production use mysql 5.6 Master/Slave replication, can I use DM to migrate data from slave?

**Comment by lance6716** [comment]
> my production use mysql 5.6 Master/Slave replication

5.6 is not supported, MySQL version should be [5.7, 8.0].

**Comment by Carl-Hee** [comment]
@lance6716  Then can I fetch data from master directly?

**Comment by lance6716** [comment]
> @lance6716 Then can I fetch data from master directly?

Yes. That version restriction is applied to the upstream database DM is connecting, so master should be in MySQL 5.7~8.0 or MariaDB >=10.1.3

And a pre-check should tell you if upstream is supported at the beginning of `start-task`

**Comment by Carl-Hee** [comment]
@lance6716  Got it. Thanks for your substantial reply

**Comment by Carl-Hee** [comment]
I wondering why the document also mentioned:
5.5 < MySQL version < 8.0

**Comment by Carl-Hee** [comment]
I wondering why the document also mentioned:
5.5 < MySQL version < 8.0

Is that means the scenario is the single db instance? what the big differences between mysql 5.6 and 5.7 so that DM is not support pervious version

**Comment by lance6716** [comment]
> Is that means the scenario is the single db instance?
Yes

> what the big differences between mysql 5.6 and 5.7 so that DM is not support pervious version
mainly MySQL internal replication stuffs

**Comment by Carl-Hee** [comment]
> mainly MySQL internal replication stuffs
I got it, from 5.7 it support multi-source replication. If the upstream structure is single master- single secondary, can DM cover such scenario?

**Comment by lance6716** [comment]
> > mainly MySQL internal replication stuffs
> 
> I got it, from 5.7 it support multi-source replication. If the upstream structure is single master- single secondary, can DM cover such scenario?

For MySQL <= 5.7.1, there's many bugs (we didn't know exactly how to trigger some of them) that often break DM's sync process. You may try single master single secondary sync
