### ISSUE TITLE
should split DDL for `ADD COLUMN (c1 int, c2 int)`

### ISSUE THREAD

**Issue by lance6716** [pingcap/dm#1339]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

in upstream. 

```
ALTER TABLE `all_mode`.`t1` ADD COLUMN (`t6` INT, `t7` INT)
```

2. What did you expect to see?

sync to downstream, split same as

```
alter table t1 add column t6 int, add column t7 int;
```

3. What did you see instead?

```

                                "Message": "startLocation: [position: (mysql-bin.000001, 1902), gtid-set: 09bec856-ba95-11ea-850a-58f2b4af5188:1-8], endLocation: [position: (mysql-bin.000001, 2026), gtid-set: ]: execute statement failed: ALTER TABLE `all_mode`.`t1` ADD COLUMN (`t6` INT, `t7` INT)",
                                "RawCause": "Error 8200: Unsupported multi schema change",
```

4. Versions of the cluster

    - DM version (run `dmctl -V` or `dm-worker -V` or `dm-master -V`):

        master

**Comment by csuzhangxc** [comment]
`alter table t1 add column t6 int, add column t7 int;` should have been split to 

```
alter table t1 add column t6 int;
alter table t1 add column t7 int;
```

but not split ```ALTER TABLE `all_mode`.`t1` ADD COLUMN (`t6` INT, `t7` INT)```, right?

**Comment by lance6716** [comment]
> `alter table t1 add column t6 int, add column t7 int;` should have been split to
> 
> ```
> alter table t1 add column t6 int;
> alter table t1 add column t7 int;
> ```
> 
> but not split `` ALTER TABLE `all_mode`.`t1` ADD COLUMN (`t6` INT, `t7` INT) ``, right?

Yes. I think DM should split `ADD COLUMN (xx, xx)` same way as `ADD COLUMN xx, ADD COLUMN xx`
