### ISSUE TITLE
Support show lags in CLI and grafana

### ISSUE THREAD

**Issue by hcymysql** [pingcap/dm#1347]
类似MySQL的seconds-behind_master

--

like MySQL seconds-behind_master

**Comment by lance6716** [comment]
2.0目前确实没有这种功能，估计可以实现成 “Relay组件获取的binlog时间戳 - sync组件已同步的时间戳”。为了与现有交互一致，可能会放到prometheus监控指标以及query-status的输出里。

**Comment by hcymysql** [comment]
> 
> 
> 2.0目前确实没有这种功能，估计可以实现成 “Relay组件获取的binlog时间戳 - sync组件已同步的binlog时间戳”。为了与现有交互一致，可能会放到prometheus监控指标以及query-status的输出里。

希望能尽快出一个哈，监控这块还是交给我们写脚本实现微信报警。

**Comment by lance6716** [comment]
目前我们开发紧张，能否帮我们贡献一下代码。预期实现是在query-status的binlog position附近带上binlog timestamp，内部实现就是在处理binlog的时候顺便保存一下timestamp

可以在这里讨论，或者 https://github.com/pingcap/dm#contributing 加入我们的slack

**Comment by lance6716** [comment]
implemented in v2.0.4
