### ISSUE TITLE
relay: invalid GTID format, must UUID:interval

### ISSUE THREAD

**Issue by GMHDBJD** [pingcap/dm#1379]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.
worker bound source from mysql to mariadb
2. What did you expect to see?
task runs well
3. What did you see instead?
```
some error occurs in dm-worker: ErrCode:30003 ErrClass:\"relay-unit\" ErrScope:\"internal\" ErrLevel:\"high\" Message:\"initial relay unit: load meta data\" RawCause:\"invalid GTID format, must UUID:interval[:interval]\"
```
[chaos](https://github.com/pingcap/dm/pull/1370/checks?check_run_id=1701081954)

**Comment by lance6716** [comment]
should be closed by #1385
