### ISSUE TITLE
relay's behaviour should align with MySQL when using GTID

### ISSUE THREAD

**Issue by lance6716** [pingcap/dm#1383]
## Bug Report

https://dev.mysql.com/doc/refman/5.7/en/replication-gtids-auto-positioning.html

> The source responds by sending all transactions recorded in its binary log whose GTID is not included in the GTID set sent by the replica. To do this, the source first identifies the appropriate binary log file to begin working with, by checking the Previous_gtids_log_event in the header of each of its binary log files, starting with the most recent. When the source finds the first Previous_gtids_log_event which contains no transactions that the replica is missing, it begins with that binary log file. This method is efficient and only takes a significant amount of time if the replica is behind the source by a large number of binary log files. The source then reads the transactions in that binary log file and subsequent files up to the current one, sending the transactions with GTIDs that the replica is missing, and skipping the transactions that were in the GTID set sent by the replica. The elapsed time until the replica receives the first missing transaction depends on its offset in the binary log file. This exchange ensures that the source only sends the transactions with a GTID that the replica has not already received or committed. If the replica receives transactions from more than one source, as in the case of a diamond topology, the auto-skip function ensures that the transactions are not applied twice.

1. `getPosByGTID` may choose start position by 
    
    choose a relay log file that its "Previous_gtids_log_event" don't overlap with "complementary set of given GTID set", which could reduce to "Previous_gtids_log_event" is subset or equal to "given GTID set"
    
2. scan the relay log and skip the transactions in "given GTID set", to handle cases when given GTID set is not continuous like `uuid:1-10:20-30`

**Comment by lance6716** [comment]
when MySQL use GTID replication and slave didn't enable binlog, user can't use slave as upstream of DM because DM is based on binlog replication. Assuming at that time the GTID set is
```
xxx:1-10
```
User enables binlog on slave then, the first binlog of slave will have an empty `Previous_gtids`, and next binlog files will have `Previous_gtids` starting from `11`. Meanwhile `select * from mysql.gtid_executed` will output GTID set starting from 1.

**Comment by GMHDBJD** [comment]
Did you use MASTER_AUTO_POSITION = 1 ?

**Comment by lance6716** [comment]
> Did you use `MASTER_AUTO_POSITION = 1` ?

didn't use it when `CHANGE MASTER`

**Comment by GMHDBJD** [comment]
What's the output of `show master status` ?

**Comment by lance6716** [comment]
> What's the output of `show master status` ?

starting from 1. accroding to MySQL doc, `show master status` will output `gtid_executed`
