### ISSUE TITLE
`DROP INDEX IF EXISTS` does not support mysql

### ISSUE THREAD

**Issue by recall704** [pingcap/dm#1384]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.
migrate data from mysql to mysql

2. What did you expect to see?

3. What did you see instead?
Error 1064: You have an error in your SQL syntax;

```
Error 1064: You have an error in you SQL syntax; check the manual that corresponds TO your MySOL server version for the right syntax to use near 'IF EXISTS
```

4. Versions of the cluster

    - DM version (run `dmctl -V` or `dm-worker -V` or `dm-master -V`):

       v1.0.6

**Comment by recall704** [comment]
reproduce：

- create table
```
CREATE TABLE `t_test` (
  `status_id` int(11) NOT NULL AUTO_INCREMENT,
  `free_prd_id` int(11) DEFAULT NULL,
  `status` tinyint(4) DEFAULT NULL,
  `create_time` datetime NOT NULL,
  PRIMARY KEY (`status_id`),
  KEY `ind_prd_id` (`free_prd_id`),
  KEY `idx_free_prd_id` (`free_prd_id`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8

```
- run dm/syncer
- drop index from source db
```
DROP INDEX `ind_prd_id` ON `t_test`
```

**Comment by lance6716** [comment]
thanks, will try reproducing later

**Comment by recall704** [comment]
in fact, mysql does not support syntax `IF EXISTS` when use `DROP INDEX`, but TiDB does.

if you want migrate data to mysql, you need change the code:

https://github.com/pingcap/dm/blob/v2.0.1/pkg/parser/common.go#L225 change IfExists to false

**Comment by lance6716** [comment]
DM is built to migrate data from MySQL/MariaDB to TiDB, so DM rewrites some statements by default to better support TiDB's scenario. You could fork DM and change that option as you like.

I will close this issue after all of your questions are answered.

**Comment by recall704** [comment]
yes, thanks for your reply.

also hope this issue can help some others
