### ISSUE TITLE
handle user specified `meta.binlog-gtid` in task but not `relay-binlog-gtid`

### ISSUE THREAD

**Issue by lance6716** [pingcap/dm#1394]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Relay unit automaticly start sync relay log from latest GTID set if not specified `relay-binlog-gtid`, and in most cases the `meta.binlog-gtid` user set is earlier that latest GTID set.

**Describe the feature you'd like:**

switch to remote binlog or refuse start task ?

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by GMHDBJD** [comment]
I think we should report an error since sync cannot find the collect relay log

**Comment by lance6716** [comment]
Yes, and I agress that relay unit should pull binlog files as-is, thus should use Previous_gtid_events rather than latest GTID to start sync

**Comment by lance6716** [comment]
> I think we should report an error since sync cannot find the collect relay log

tested in current master, close this issue
