### ISSUE TITLE
Check task configuration is referenced

### ISSUE THREAD

**Issue by 3pointer** [pingcap/dm#1409]
## Feature Request

**Is your feature request related to a problem? Please describe:**

if the user set `safe-mode` in the`task.yaml`,  but forgot to refer this configuration with `syncer-config-name`, then this configuration is missing. and `safe-mode` will be the default value(false).

**Describe the feature you'd like:**

Clearly tell user that some configuration in `task.yaml` is not referenced when the task started.

**Describe alternatives you've considered:**

Other tools Lightning/TiUP/TiCDC may need this check too.

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by lance6716** [comment]
close by #1410
