### ISSUE TITLE
Support upstream SHOW MASTER STATUS has not continuous GTID set

### ISSUE THREAD

**Issue by lance6716** [pingcap/dm#1418]
## Feature Request

**Is your feature request related to a problem? Please describe:**

need to test if upstream `SHOW MASTER STATUS` output a not continuous GTID set like

```
uuid:1-100:103-200
```

DM will handle it properly

**Describe the feature you'd like:**

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by lance6716** [comment]
WIP: seems we should start gtid sync at `previous_gtid_events` + `@@global.gtid_purged before that last GTID of previous_gtid_events`

**Comment by lance6716** [comment]
we could manually specify `gtid_next` to reproduce a not conctinous GTID set

```sql
set session gtid_next='uuid:gtid'
insert into ...
```

**Comment by GMHDBJD** [comment]
We can use `change master to master_log_file,master_log_pos` without master_auto_position to reproduce a not continous GTID set.
e.g.
```
change master to MASTER_AUTO_POSITION=1;
start slave; ---> 1-xxx
stop slave;
insert into master mysql.
change master to master_log_file,master_log_pos; ---> start from yyy.
start slave;  ---> 1-xxx:yyy-zzz
```

**Comment by GMHDBJD** [comment]
> seems we should start gtid sync at previous_gtid_events + @@global.gtid_purged before that last GTID of previous_gtid_events

Could not understand.

**Comment by lance6716** [comment]
> > seems we should start gtid sync at previous_gtid_events + @@global.gtid_purged before that last GTID of previous_gtid_events
> 
> Could not understand.

updated, PTAL

**Comment by GMHDBJD** [comment]
The only way I can think of which would cause `ERROR 1236 (HY000): The slave is connecting using CHANGE MASTER TO MASTER_AUTO_POSITION = 1, but the master has purged binary logs containing GTIDs that the slave requires` by a gset not start from 1 is:

DM sync from a slave mysql
```
master <-- slave <-- DM
```

master's previous gtid event: 1-xxx
slave's previous gtid event: yyy-xxx
so DM relay's previous gtid event: yyy-xxx
When we get a gtid from pos zzz between yyy and xxx, we will get a gtid set : yyy-zzz.
Now if we start sync yyy-zzz from slave, no errors will occur.
But if we sync yyy-zzz from master, above error may occur if master has purge some relay log.

**Comment by lance6716** [comment]
> The only way I can think of which would cause `ERROR 1236 (HY000): The slave is connecting using CHANGE MASTER TO MASTER_AUTO_POSITION = 1, but the master has purged binary logs containing GTIDs that the slave requires` by a gset not start from 1 is:
> 
> DM sync from a slave mysql
> 
> ```
> master <-- slave <-- DM
> ```
> 
> master's previous gtid event: 1-xxx
> slave's previous gtid event: yyy-xxx
> so DM relay's previous gtid event: yyy-xxx
> When we get a gtid from pos zzz between yyy and xxx, we will get a gtid set : yyy-zzz.
> Now if we start sync yyy-zzz from slave, no errors will occur.
> But if we sync yyy-zzz from master, above error may occur if master has purge some relay log.

an evil user may reset the GTID, manually set `gtid_next` to some value larger than 1 and do some insert, rotate binlog. So when there's `Previous_gtids` not starting at 1, we may not reset the start by looking at `gtid_purged`

and currently ResetStart will cause `xxx:1-20:40-60` become `xxx:1-20:1-60`

**Comment by lance6716** [comment]
```sql
mysql> show binlog events in 'mysql-bin.000007' limit 2;
+------------------+-----+----------------+-----------+-------------+--------------------------------------------+
| Log_name         | Pos | Event_type     | Server_id | End_log_pos | Info                                       |
+------------------+-----+----------------+-----------+-------------+--------------------------------------------+
| mysql-bin.000007 |   4 | Format_desc    |    123456 |         123 | Server ver: 5.7.32-35-log, Binlog ver: 4   |
| mysql-bin.000007 | 123 | Previous_gtids |    123456 |         194 | ddb8974e-6064-11eb-8357-0242ac110002:17-18 |
+------------------+-----+----------------+-----------+-------------+--------------------------------------------+

mysql> show binlog events in 'mysql-bin.000001' limit 2;
+------------------+-----+----------------+-----------+-------------+------------------------------------------+
| Log_name         | Pos | Event_type     | Server_id | End_log_pos | Info                                     |
+------------------+-----+----------------+-----------+-------------+------------------------------------------+
| mysql-bin.000001 |   4 | Format_desc    |    123456 |         123 | Server ver: 5.7.32-35-log, Binlog ver: 4 |
| mysql-bin.000001 | 123 | Previous_gtids |    123456 |         154 |                                          |
+------------------+-----+----------------+-----------+-------------+------------------------------------------+
```

```golang
package main

import (
	"context"
	"os"

	"github.com/siddontang/go-mysql/mysql"
	"github.com/siddontang/go-mysql/replication"
)

func main() {
	g1, _ := mysql.ParseMysqlGTIDSet("ddb8974e-6064-11eb-8357-0242ac110002:17-18")

	cfg := replication.BinlogSyncerConfig {
		ServerID: 100,
		Flavor:   "mysql",
		Host:     "172.16.5.169",
		Port:     3323,
		User:     "root",
		Password: "",
	}
	syncer := replication.NewBinlogSyncer(cfg)
	streamer, err := syncer.StartSyncGTID(g1)
	if err != nil {
		panic(err)
	}

	for {
		ev, _ := streamer.GetEvent(context.Background())
		// Dump event
		ev.Dump(os.Stdout)
	}
}
```

result
```
[2021/02/04 17:16:11] [error] binlogstreamer.go:77 close sync with err: ERROR 1236 (HY000): The slave is connecting using CHANGE MASTER TO MASTER_AUTO_POSITION = 1, but the master has purged binary logs containing GTIDs that the slave requires. Replicate the missing transactions from elsewhere, or provision a new slave from backup. Consider increasing the master's binary log expiration period. The GTID set sent by the slave is 'ddb8974e-6064-11eb-8357-0242ac110002:17-18', and the missing transactions are 'ddb8974e-6064-11eb-8357-0242ac110002:1-16'.
```
