### ISSUE TITLE
tests: wrong configuration of all model integration test

### ISSUE THREAD

**Issue by hidehalo** [pingcap/dm#1435]
## Bug Report

1. What did you do? If possible, provide a recipe for reproducing the error.

If you are doing integration tests, it will show us:

```
[2021/02/04 23:14:12.730 +08:00] [ERROR] [main.go:38] ["parse cmd flags"] [error="unknown keys in config file /dm/tests/all_mode/conf/diff_config.toml: [use-rowid source-db.sql-mode source-db.sql-mode]"] [errorVerbose="unknown keys in config file /dm/tests/all_mode/conf/diff_config.toml: [use-rowid source-db.sql-mode source-db.sql-mode]
main.(*Config).configFromFile
	/tidb-tools/sync_diff_inspector/config.go:282
main.(*Config).Parse
	/tidb-tools/sync_diff_inspector/config.go:248
main.main
	/tidb-tools/sync_diff_inspector/main.go:32
runtime.main
	/usr/local/Cellar/go/1.15.7/libexec/src/runtime/proc.go:204
runtime.goexit
	/usr/local/Cellar/go/1.15.7/libexec/src/runtime/asm_amd64.s:1374"] [stack="main.main
	/tidb-tools/sync_diff_inspector/main.go:38
runtime.main
	/usr/local/Cellar/go/1.15.7/libexec/src/runtime/proc.go:204"]
...
make: *** [integration_test] Error 1
```

2. What did you expect to see?

`make integration_test` exit 0

3. What did you see instead?

make: *** [integration_test] Error 1

4. Versions of the cluster

    - DM version:

        ```
        efa5b30ee9be9293305ab78a202484b0281ce169
        ```

    - Upstream MySQL/MariaDB server version:

        ```
        5.7
        ```

    - Downstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

        ```
        Release Version: v4.0.0-beta.2-2053-g05d995d73-dirty
        Edition: Community
        Git Commit Hash: 05d995d73d236077cf8883e7950d650b7e4a50a5
        Git Branch: rel
        UTC Build Time: 2021-01-26 14:11:43
        GoVersion: go1.15.7
        Race Enabled: false
        TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
        Check Table Before Drop: false
        ```

    - How did you deploy DM: DM-Ansible or manually?

        ```
        no
        ```

    - Other interesting information (system version, hardware config, etc):

        >Darwin rmbp.local.cc 18.7.0 Darwin Kernel Version 18.7.0: Thu Jun 18 20:50:10 PDT 2020; root:xnu-4903.278.43~1/RELEASE_X86_64 x86_64

**Comment by lance6716** [comment]
Thanks. Seems they are not needed.
use-rowid is removed in https://github.com/pingcap/tidb-tools/pull/253
sql-mode is removed in https://github.com/pingcap/tidb-tools/pull/381

**Comment by hidehalo** [comment]
> Thanks. Seems they are not needed.
> use-rowid is removed in [pingcap/tidb-tools#253](https://github.com/pingcap/tidb-tools/pull/253)
> sql-mode is removed in [pingcap/tidb-tools#381](https://github.com/pingcap/tidb-tools/pull/381)

Thank you!
