### ISSUE TITLE
dmctl增加任务批量展示命令

### ISSUE THREAD

**Issue by alwaystest18** [pingcap/dm#144]
我们这边线上已经使用了20多个worker，希望dmctl增加批量任务展示的界面，类似supervisor的任务管理，仅展示任务名称及任务状态，目前的query-status输出信息太多了，如果我想查看全部任务哪些存在异常，只能通过报警功能

**Comment by ericsyh** [comment]
@alwaystest18 你好，我们目前在 dm v1.0.2 版本中添加了批量任务展示功能，可以看下 [DM 查询状态](https://pingcap.com/docs-cn/v3.0/reference/tools/data-migration/query-status/) 中的示例效果
