### ISSUE TITLE
stop-task has confused error output

### ISSUE THREAD

**Issue by Tammyxia** [pingcap/dm#1470]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.
Execute "stop-task" has error output, this is confused because the error is not about stop-task,
user will think "stop-task" failed with error, but actually stop-task is successfully, the error is about DM other background function error.
2. What did you expect to see?
Maybe it's better that DM background function errors print in screen immmediately, while not print in stop-stask output. 
3. What did you see instead?
4. [root@CentOS76_VM home]# tiup dmctl --master-addr 172.16.4.214:8261 stop-task /home/task-relay.yaml
Starting component `dmctl`: /root/.tiup/components/dmctl/v2.0.1/dmctl/dmctl --master-addr 172.16.4.214:8261 stop-task /home/task-relay.yaml
{
    "op": "Stop",
    "result": true,
    "msg": "",
    "sources": [
        {
            "result": false,
            "msg": "[code=38032:class=dm-master:scope=internal:level=high], Message: some error occurs in dm-worker: ErrCode:40067 ErrClass:\"dm-worker\" ErrScope:\"internal\" ErrLevel:\"high\" Message:\"waiting for relay to catch up with loader is timeout (exceeding 5m0s), loader: (mysql-bin.000135, 776111422), relay: (mysql-bin.000085, 147762084)\" , Workaround: Please execute `query-status` to check status.",
            "source": "mysql-replica31",
            "worker": "dm-172.16.5.108-8262"
        }
    ]
}

4. Versions of the cluster

    - DM version (run `dmctl -V` or `dm-worker -V` or `dm-master -V`):

        ```
        v2.0.1
        ```

    - Upstream MySQL/MariaDB server version:

        ```
        (paste upstream MySQL/MariaDB server version here)
        ```

    - Downstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

        ```
        (paste TiDB cluster version here)
        ```

    - How did you deploy DM: DM-Ansible or manually?

        ```
        (leave DM-Ansible or manually here)
        ```

    - Other interesting information (system version, hardware config, etc):

        >
        >

5. current status of DM cluster (execute `query-status` in dmctl)

6. Operation logs
   - Please upload `dm-worker.log` for every DM-worker instance if possible
   - Please upload `dm-master.log` if possible
   - Other interesting logs
   - Output of dmctl's commands with problems
   
7. Configuration of the cluster and the task
   - `dm-worker.toml` for every DM-worker instance if possible
   - `dm-master.toml` for DM-master if possible
   - task config, like `task.yaml` if possible
   - `inventory.ini` if deployed by DM-Ansible

8. Screenshot/exported-PDF of Grafana dashboard or metrics' graph in Prometheus for DM if possible

**Comment by lance6716** [comment]
user may not deploy alerting nodes, so the output of command is the only change to tell erorrs
