### ISSUE TITLE
Document issue about dm deployment environment

### ISSUE THREAD

**Issue by Tammyxia** [pingcap/dm#1474]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.
Page: https://docs.pingcap.com/zh/tidb-data-migration/stable/hardware-and-software-requirements#%E7%94%9F%E4%BA%A7%E7%8E%AF%E5%A2%83 -> Chinese webpage
https://docs.pingcap.com/tidb-data-migration/stable/hardware-and-software-requirements ->English webpage

There's info:
1. In the production environment, DM-master and DM-worker can be deployed and run on the same server. 
在生产环境中，DM-master 和 DM-worker 可以部署和运行在同一个服务器上。

 2. 开发及测试环境
组件 | CPU | 内存 | 本地存储 | 网络 | 实例数量（最低要求）
-- | -- | -- | -- | -- | --
DM-worker | 8 核+ | 16 GB+ | **SAS**，200 GB+（大于迁移数据的大小） | 千兆网卡 | 上游 MySQL 实例的数量

2. What did you expect to see?
   I.  In the production environment, it's better to deploy  DM-master and DM-worker in different server.
   II. When enable relay log, even in development/test env, dm-worker requires ssd disk(not SAS HDD), otherwize you will meet  disk I/O slow issue in dm-worker node.
3. What did you see instead?

4. Versions of the cluster

    - DM version (run `dmctl -V` or `dm-worker -V` or `dm-master -V`):

        ```
        v2.0.1
        ```

    - Upstream MySQL/MariaDB server version:

        ```
        (paste upstream MySQL/MariaDB server version here)
        ```

    - Downstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

        ```
        (paste TiDB cluster version here)
        ```

    - How did you deploy DM: DM-Ansible or manually?

        ```
        (leave DM-Ansible or manually here)
        ```

    - Other interesting information (system version, hardware config, etc):

        >
        >

5. current status of DM cluster (execute `query-status` in dmctl)

6. Operation logs
   - Please upload `dm-worker.log` for every DM-worker instance if possible
   - Please upload `dm-master.log` if possible
   - Other interesting logs
   - Output of dmctl's commands with problems
   
7. Configuration of the cluster and the task
   - `dm-worker.toml` for every DM-worker instance if possible
   - `dm-master.toml` for DM-master if possible
   - task config, like `task.yaml` if possible
   - `inventory.ini` if deployed by DM-Ansible

8. Screenshot/exported-PDF of Grafana dashboard or metrics' graph in Prometheus for DM if possible

**Comment by lance6716** [comment]
doc has been updated. close
