### ISSUE TITLE
Check important environment variables

### ISSUE THREAD

**Issue by overvenus** [pingcap/dm#1482]
## Feature Request

Some important environment variables  affects BR and TiDB-Lightning, eg. http_proxy which may break gRPC connection.

The following link is how TiKV checks environment variables, we can do the same.

https://github.com/tikv/tikv/blob/2cee812f236e3134c9df8b37e73ac51a5f90690f/components/tikv_util/src/lib.rs#L509

**Comment by lance6716** [comment]
specifically, 
- we could add a WARN log when proxies are set in DM master and worker
- we could print warning message to stdout when using dmctl, and this could be suppressed by a flag

**Comment by lance6716** [comment]
https://github.com/pingcap/ticdc/pull/1492
