### ISSUE TITLE
task state is not deleted in prometheus when task is stopped

### ISSUE THREAD

**Issue by lichunzhu** [pingcap/dm#1594]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.
When task on dm-worker is re-scheduled, the task state on the original worker will become `stopped` unless this worker is restarted, which looks confusing.

2. What did you expect to see?
This prometheus state is deleted.

3. What did you see instead?
It becomes `stopeed`.

4. Versions of the cluster

    - DM version (run `dmctl -V` or `dm-worker -V` or `dm-master -V`):

        ```
        v2.0.2
        ```

**Comment by lance6716** [comment]
> @lichunzhu: The label(s) `affected-v2.0.2,severity/minor` cannot be applied. These labels are supported: `Hacktoberfest, TiDB-5.0, already-cherry-pick-1.0, already-cherry-pick-2.0, already-update-dm-ansible, already-update-docs, already-update-release-note, dependencies, good first issue, help wanted, high-performance, hptc, javascript, needs-cherry-pick-1.0, needs-cherry-pick-2.0, needs-update-dm-ansible, needs-update-docs, needs-update-release-note, question, release-track`.

I didn't add these labels in a way that bot could recognized 😂 You could fire a PR to change bot config if you want
