### ISSUE TITLE
load unit can't load data with `"` in the table name

### ISSUE THREAD

**Issue by csuzhangxc** [pingcap/dm#167]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

loading data with `"` in the table.

2. What did you expect to see?

data loaded.

3. What did you see instead?

_paserpkg_ parse SQL statement fail because not using the correct `sql-mode`.

4. Versions of the cluster

    - DM version (run `dmctl -V` or `dm-worker -V` or `dm-master -V`):

        ```
        before this commit (https://github.com/pingcap/dm/tree/cd743e564306a9ef103460a0a446359ae711e21d)
        ```

**Comment by GMHDBJD** [comment]
Now we support `session` in task config to set sql_mode, and `enable-ansi-quotes` to parse SQL. Close this issure.

**Comment by csuzhangxc** [comment]
@GMHDBJD are there any manual/automatical tests to verify this?

**Comment by GMHDBJD** [comment]
After manual test, we currently not support in loader, will support it later 😥
