### ISSUE TITLE
CREATE TABLE IF NOT EXISTS may causes error like `Column count doesn't match value count: x (columns) vs y (values)`

### ISSUE THREAD

**Issue by lance6716** [pingcap/dm#1697]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.
https://asktug.com/t/topic/92863

   1. at upstream: create table test.t (c int primary key); 
   2. start a "all" mode task
   3. at upstream: create table if not exists test.t (c1 int, c2 int); insert into test.t values (1);
   4. query-status

2. What did you expect to see?
no error

3. What did you see instead?
gen insert sqls failed, schema: test, table: t: Column count doesn't match value count: 2 (columns) vs 1 (values)"

**Comment by Ehco1996** [comment]
`create table test.t if not exists t (c1 int, c2 int); insert into test.t values (1);` -> mysql syntas err

should update to ` create table if not exists test.t (c1 int, c2 int); insert into test.t values (1);`
