### ISSUE TITLE
[ddl:8216]Invalid auto random: column uuid is not the integer primary key, or the primary key is nonclustered

### ISSUE THREAD

**Issue by glkappe** [pingcap/dm#1715]
dm version: v2.0.3
tiup & tiup-dm: v1.4.3

Table structure and data have been desensitized

This is a requirement for multiple data sources to merge tables

mysql：
⁣CREATE TABLE `a_1` (
  `id` bigint(20) NOT NULL,
  `uid` bigint(20) NOT NULL,
  `a` tinyint(1) NOT NULL DEFAULT '0',
  `b` tinyint(1) NOT NULL DEFAULT '0',
  `c` int(11) NOT NULL,
  `d` text COLLATE utf8mb4_unicode_ci NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
⁣⁣
⁣
tidb：
⁣CREATE TABLE `a` (
  `uuid` bigint(20) NOT NULL AUTO_RANDOM,
  `id` bigint(20) NOT NULL,
  `uid` bigint(20) NOT NULL,
  `a` tinyint(1) NOT NULL DEFAULT '0',
  `b` tinyint(1) NOT NULL DEFAULT '0',
  `c` int(11) NOT NULL,
  `d` text COLLATE utf8mb4_unicode_ci NOT NULL,
  PRIMARY KEY (`uuid`)
  KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

query-status info：
query-status asd
{
    "result": true,
    "msg": "",
    "sources": [
        {
            "result": true,
            "msg": "",
            "sourceStatus": {
                "source": "cnf",
                "worker": "xxxx",
                "result": null,
                "relayStatus": null
            },
            "subTaskStatus": [
                {
                    "name": "testtask",
                    "stage": "Paused",
                    "unit": "Sync",
                    "result": {
                        "isCanceled": false,
                        "errors": [
                            {
                                "ErrCode": 44003,
                                **"ErrClass": "schema-tracker",**
                                "ErrScope": "downstream",
                                "ErrLevel": "high",
                                **"Message": "startLocation: [position: (, 0), gtid-set: ], endLocation: [position: (mysql-bin.0073, 858627), gtid-set: 3580cb9-11e7-b133-525400bc861-125176714,3e8ecf-3b9-11e7-b133-5254005d54:1-135811]: failed to create table for `test`.`a_1` in schema tracker",
                                "RawCause": "[ddl:8216]Invalid auto random: column uuid is not the integer primary key, or the primary key is nonclustered",**
                                "Workaround": ""
                            }
                        ],
                        "detail": null
                    },
                    "unresolvedDDLLockID": "",
                    "sync": {
                        "totalEvents": "0",
                        "totalTps": "0",
                        "recentTps": "0",
                        "masterBinlog": "(mysql-bin.004, 694)",
                        "masterBinlogGtid": "35b18-3eb-11e7-b13-6:1-1252063311e2ecf-3e11e7-b133-0095d541-170535811",
                        "syncerBinlog": "(mysql-bin.0013, 85284)",
                        "syncerBinlogGtid": "3580cb18-3eb9-17-b133-52540bc986:1-1517714,3ecf-3eb11e7-b1-524d54:1-0535811",
                        "blockingDDLs": [
                        ],
                        "unresolvedGroups": [
                        ],
                        "synced": false,
                        "binlogType": "remote"
                    }
                }
            ]
        },

**Comment by Ehco1996** [comment]
@glkappe  could you please provide the task conifg?

**Comment by lance6716** [comment]
current plan: drop auto_random when restore SQL 
cc @lysu is there other SQL pattern that needs out special treatment?
