### ISSUE TITLE
`dmctl` could read `master-addr` from environment variables

### ISSUE THREAD

**Issue by lance6716** [pingcap/dm#1720]
## Feature Request

**Is your feature request related to a problem? Please describe:**

**Describe the feature you'd like:**

```shell
export MASTER_ADDR="127.0.0.1:8261"
./dmctl query-status
```

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by Ehco1996** [comment]
i think env with namespace such as `DM_MASTER_ADD` is better ?
