### ISSUE TITLE
reduce ci running time

### ISSUE THREAD

**Issue by Ehco1996** [pingcap/dm#1727]
## Feature Request

**Is your feature request related to a problem? Please describe:**

now one success test ci spend more than 18m, we want to reduce this time to 13m.

[jenkins](https://ci.pingcap.net/blue/organizations/jenkins/dm_ghpr_new_test/detail/dm_ghpr_new_test/359/pipeline)

**Describe the feature you'd like:**

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by lance6716** [comment]
could close now?
