### ISSUE TITLE
Task auto resume after manually pause an error task.

### ISSUE THREAD

**Issue by GMHDBJD** [pingcap/dm#1729]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.
upstream report an error after start/resume task immediately. (e.g. failed to create table)
task auto-resume
fail to execute `operate-schema` because task not pause
2. What did you expect to see?
manually pause task
exec `operate-schema set`
3. What did you see instead?
pause task fails because error immediately occur after auto resume, we can't pause a paused task.
operate-schema fails because task auto-resume since it's paused by error
4. Versions of the cluster

    - DM version (run `dmctl -V` or `dm-worker -V` or `dm-master -V`):

        ```
        master
        ```

**Comment by GMHDBJD** [comment]
We may need to pause a "paused" task which is pause by error.

**Comment by glkappe** [comment]
v2.0.3 have same question.
The scenario used may be that when there are thousands of sub-table schemas that need to be set, the establishment of auto_resume cannot be completely satisfied
