### ISSUE TITLE
operate-schema set --flush may cause dm-worker server to restart

### ISSUE THREAD

**Issue by glkappe** [pingcap/dm#1730]
dm version：v2.0.3

operate-schema set --flush may cause dm-worker server to restart，This is an abnormal restart

dm-worker log：
｛Because the operate-schema set --flush operation is executed multiple times, there are many restarts, and only the screenshot information of the restart is shown here.｝

![image](https://user-images.githubusercontent.com/21033020/119849710-6ef00280-bf3f-11eb-99a2-7d063d55bbe0.png)

std error
[stderr.txt](https://github.com/pingcap/dm/files/6554936/stderr.txt)

**Comment by GMHDBJD** [comment]
https://github.com/pingcap/dm/issues/1724#issuecomment-849516489 It's a bug if we use --flush to create a table structure for fresh new tables

**Comment by glkappe** [comment]
How to understand the definition of the new table, currently dm task is in sync state

**Comment by GMHDBJD** [comment]
Syncer meet the table for the first time(no checkpoint for that table before)

**Comment by lance6716** [comment]
closed by #1799
