### ISSUE TITLE
SQL mode is still not automatic enough

### ISSUE THREAD

**Issue by lance6716** [pingcap/dm#1735]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Currently DM will query global SQL Mode of upstream to sync. When user set a session level one, the inconsistent of SQL mode may cause an error

**Describe the feature you'd like:**

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by together-wang** [comment]
sql_mode automatic matching error

NO_ZERO_DATE exists in upstream sql_mode, and downstream sql_mode is empty
When the old table with zero_date in the upstream is synchronized through DM, the error Invalid default value is reported, and it is not automatically matched to the downstream sql_mode

![image](https://user-images.githubusercontent.com/44355590/120608811-2dea7780-c484-11eb-97b6-a01f04e9a817.png)
![image](https://user-images.githubusercontent.com/44355590/120608854-38a50c80-c484-11eb-9417-c21f78f53d03.png)
![image](https://user-images.githubusercontent.com/44355590/120609013-5ffbd980-c484-11eb-84ef-4571f1d20778.png)
![image](https://user-images.githubusercontent.com/44355590/120609322-a4877500-c484-11eb-9ae5-d1e68be2074c.png)
![image](https://user-images.githubusercontent.com/44355590/120609486-caad1500-c484-11eb-9396-1c912af976d6.png)
