### ISSUE TITLE
When will rollback checkpoint be triggered

### ISSUE THREAD

**Issue by GdCwh** [pingcap/dm#1739]
At present, when can not find first log file name in binary log index file appears, rollback checkpoint be triggered

We want to know if there are any other situations that trigger a rollback checkpoint？

**Comment by lance6716** [comment]
Does "can not find first log file name in binary log index file appears" means MySQL purged its binlog?

DM has many types of checkpoints, one is flushed checkpoint which is the ground truth of sync progress, another is a memory checkpoint to be flushed. When error happens and task pauses, the memory checkpoint is "rollbacked" to flushed checkpoint.

You could turn to https://asktug.com/tags/dm for Chinese discussion.
