### ISSUE TITLE
dm sync error

### ISSUE THREAD

**Issue by pzj6868** [pingcap/dm#1795]
dm version:  v2.0.4
tidb version: v5.0.0
mysql version: 5.7
dm subtask paused where progress 94%
        "subTaskStatus": [
                {
                    "name": "apv10",
                    "stage": "Paused",
                    "unit": "Load",
                    "result": {
                        "isCanceled": false,
                        "errors": [
                            {
                                "ErrCode": 34009,
                                "ErrClass": "load-unit",
                                "ErrScope": "internal",
                                "ErrLevel": "high",
                                "Message": "restore data file (apv.xxx.000000123.sql) failed: invalid insert sql

How to solve the problem?

**Comment by lance6716** [comment]
please provide more detailed information

- log file of this DM worker
- apv.xxx.000000123.sql

and you could turn to https://asktug.com/tags/dm for help

**Comment by lance6716** [comment]
@pzj6868 Hi, please take a look at my request
