### ISSUE TITLE
secondsBehindMaster didn't return 0 after workload is gone

### ISSUE THREAD

**Issue by lance6716** [pingcap/dm#1798]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

https://asktug.com/t/topic/93842

2. What did you expect to see?

3. What did you see instead?

**Comment by lance6716** [comment]
we should not rely on heartbeat packet because lag should be updated more timely.

**Comment by Ehco1996** [comment]
reopen

if no job in queue, lag still not be updated
