### ISSUE TITLE
When upstream has gap in GTID sets, switching `enable-gtid` from OFF to ON will fail the synchronization

### ISSUE THREAD

**Issue by glkappe** [pingcap/dm#1814]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.
dm worker error log：
![image](https://user-images.githubusercontent.com/21033020/123254872-c58e3380-d521-11eb-9d2c-710c44757348.png)
mysql binlog info：
![image](https://user-images.githubusercontent.com/21033020/123254901-cde66e80-d521-11eb-9dad-9fdce20bd4e4.png)

query-status 03 syncerbinloggtid info：
`
  "unresolvedDDLLockID": "",
                    "sync": {
                        "totalEvents": "0",
                        "totalTps": "0",
                        "recentTps": "0",
                        "masterBinlog": "(mysql-bin.074545, 417140060)",
                        "masterBinlogGtid": "148da50a-935f-11ea-9456-0ecb2cc2c6f2:1-26025771647,5ba91a4e-2b16-11eb-8406-0af8ee284d60:1-43991284520,903b8ce1-9357-11ea-a7af-0eac1754e2d4:1-7,f5cdfc8b-2b15-11eb-ba43-0a342fdb5c6c:1-21093139382",
                        "syncerBinlog": "(mysql-bin.074534, 999293514)",
                        "syncerBinlogGtid": "148da50a-935f-11ea-9456-0ecb2cc2c6f2:23174871189-26025771647,5ba91a4e-2b16-11eb-8406-0af8ee284d60:1-43991284520,f5cdfc8b-2b15-11eb-ba43-0a342fdb5c6c:1-21082962932",
`
mysql binlog 74534 :
![image](https://user-images.githubusercontent.com/21033020/123255628-a8a63000-d522-11eb-8c02-85f34173eabd.png)

mysql master status & purged info：
![image](https://user-images.githubusercontent.com/21033020/123255978-020e5f00-d523-11eb-95dd-5b97c8f3aa6e.png)

2. What did you expect to see?
replication is stop, and error is 'gtid is purged'
3. What did you see instead?
task is running
4. Versions of the cluster

    - DM version (run `dmctl -V` or `dm-worker -V` or `dm-master -V`):
v2.0.4
        ```
        (paste DM version here, and you must ensure versions of dmctl, DM-worker and DM-master are same)
        ```

    - Upstream MySQL/MariaDB server version:
5.7-percona
        ```
        (paste upstream MySQL/MariaDB server version here)
        ```

    - Downstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):
v4.0.10
        ```
        (paste TiDB cluster version here)
        ```

    - How did you deploy DM: DM-Ansible or manually?
tiup
        ```
        (leave DM-Ansible or manually here)
        ```

    - Other interesting information (system version, hardware config, etc):

        >centos 7
        >

5. current status of DM cluster (execute `query-status` in dmctl)
task 3 is paused

6. Operation logs
   - Please upload `dm-worker.log` for every DM-worker instance if possible
   - Please upload `dm-master.log` if possible
   - Other interesting logs
   - Output of dmctl's commands with problems
   
7. Configuration of the cluster and the task
   - `dm-worker.toml` for every DM-worker instance if possible
   - `dm-master.toml` for DM-master if possible
   - task config, like `task.yaml` if possible
   - `inventory.ini` if deployed by DM-Ansible
add `enable-gtid: true` to `3`source file

8. Screenshot/exported-PDF of Grafana dashboard or metrics' graph in Prometheus for DM if possible
no

**Comment by lichunzhu** [comment]
This problem is caused by previous gtid sets may not include all purged gtid sets. MySQL reported an error when we request a purged GTID.

**Comment by lance6716** [comment]
maybe we could use `select @@global.gtid_executed;` to get a no gap GTID, will test later
