### ISSUE TITLE
log print http_proxy if has used http_proxy

### ISSUE THREAD

**Issue by knull-cn** [pingcap/dm#1838]
## Feature Request

**Is your feature request related to a problem? Please describe:**

if use env has set http_proxy, dm(grpc) will use it .
but user do not known anything about this . 
如果linux环境配置了http_proxy 环境变量，dm 会自动使用。但是用户对此一无所知。

**Describe the feature you'd like:**

can you print http_proxy info if dm was use http_proxy?
是否能在使用http_proxy的时候打印日志提示下？

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by lance6716** [comment]
duplicate with https://github.com/pingcap/dm/issues/1482
