### ISSUE TITLE
Tikv node hangup while dm job working

### ISSUE THREAD

**Issue by XuJianxu** [pingcap/dm#1875]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.
create 200*mysql upstream, 200*dm-worker 100*tasks to migrate date. to downstream tidb.

2. What did you expect to see?
No error happened, tidb can work properly.

3. What did you see instead?
Tikv was offline and system halted.
![image](https://user-images.githubusercontent.com/23207893/125900762-370f5c12-deaf-4d7c-a2b9-126633423f5b.png)

4. Versions of the cluster

    - DM version (run `dmctl -V` or `dm-worker -V` or `dm-master -V`):

        ```
        2.0.1
        ```

    - Upstream MySQL/MariaDB server version:

        ```
        100* 5.6 mysql 100*5.7 mysql
        ```

    - Downstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

        ```
        4.0.10
        ```

    - How did you deploy DM: DM-Ansible or manually?

        ```
        DM-Ansible 
        ```

    - Other interesting information (system version, hardware config, etc):

        >
        >

5. current status of DM cluster (execute `query-status` in dmctl)

6. Operation logs
   - Please upload `dm-worker.log` for every DM-worker instance if possible
   - Please upload `dm-master.log` if possible
   - Other interesting logs
   - Output of dmctl's commands with problems
   
7. Configuration of the cluster and the task
   - `dm-worker.toml` for every DM-worker instance if possible
   - `dm-master.toml` for DM-master if possible
   - task config, like `task.yaml` if possible
   - `inventory.ini` if deployed by DM-Ansible

8. Screenshot/exported-PDF of Grafana dashboard or metrics' graph in Prometheus for DM if possible

**Comment by XuJianxu** [comment]
![image](https://user-images.githubusercontent.com/23207893/125901677-690e20d5-02d0-4190-b2e0-c99577412648.png)
Add memory monitor

**Comment by lance6716** [comment]
this is a TiKV issue?

**Comment by fubinzh** [comment]
Also encountered TiKV oom issue while DM sync from MariaDB to TiDB
Upstream: MariaDB 10.0.38 
Downstream: TiDB 5.0.3 
DM: v5.0.0-nightly-20210715 

Refer to TiKV and DM-worker logs below:
[tikv.log](https://github.com/pingcap/dm/files/6828421/tikv.log)
[dm-worker.log](https://github.com/pingcap/dm/files/6828424/dm-worker.log)

**Comment by GMHDBJD** [comment]
close since it transfer to tikv repo https://github.com/tikv/tikv/issues/10580
