### ISSUE TITLE
Write conflict happened while upgrade dm V2.0.1 to nightly

### ISSUE THREAD

**Issue by XuJianxu** [pingcap/dm#1890]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.
200 upstream mysql, 200* dm worker, 3*dm master, 200K QPS+TPS in upstream.
Upgrade dm cluster from 2.0.1 to nightly。

2. What did you expect to see?
no write conflict

3. What did you see instead?
write conflict happened
![image](https://user-images.githubusercontent.com/23207893/126307351-8b5786fd-4235-4e5c-bc48-bf4467834879.png)

4. Versions of the cluster

    - DM version (run `dmctl -V` or `dm-worker -V` or `dm-master -V`):

        ```
        v2.0.1
        ```

    - Upstream MySQL/MariaDB server version:

        ```
       mysql5.6/5.7
        ```

    - Downstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

        ```
      4.0.10
        ```

    - How did you deploy DM: DM-Ansible or manually?

        ```
        DM-Ansible
        ```

    - Other interesting information (system version, hardware config, etc):

        >
        >

5. current status of DM cluster (execute `query-status` in dmctl)

6. Operation logs
   - Please upload `dm-worker.log` for every DM-worker instance if possible
   - Please upload `dm-master.log` if possible
   - Other interesting logs
   - Output of dmctl's commands with problems
   
7. Configuration of the cluster and the task
   - `dm-worker.toml` for every DM-worker instance if possible
   - `dm-master.toml` for DM-master if possible
   - task config, like `task.yaml` if possible
   - `inventory.ini` if deployed by DM-Ansible

8. Screenshot/exported-PDF of Grafana dashboard or metrics' graph in Prometheus for DM if possible

**Comment by lance6716** [comment]
write conflict may caused by https://github.com/pingcap/dm/issues/1895#issuecomment-883842676. since the write conflict still occurs at this moment, I'll try to adjust the table structure by `operate-schema` and see if the conflict is still here

**Comment by lance6716** [comment]
after setting correct table schema for every shard tables, this problem doesn't happen again.
