### ISSUE TITLE
DM replicate lag is too high while 100 upstream shard table 

### ISSUE THREAD

**Issue by XuJianxu** [pingcap/dm#1891]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.
200 upstream mysql, 200* dm worker, 3*dm master, 200K QPS+TPS in upstream.
timezone in upstream is 8 hours in advance

2. What did you expect to see?
DM delay in expect.

3. What did you see instead?
DM delay  is too high.
![image](https://user-images.githubusercontent.com/23207893/126309002-9d4e9bd7-c17c-44da-b348-fa15adddcaff.png)

4. Versions of the cluster

    - DM version (run `dmctl -V` or `dm-worker -V` or `dm-master -V`):

        ```
        nightly
        ```

    - Upstream MySQL/MariaDB server version:

        ```
        mysql5.6/5.7
        ```

    - Downstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

        ```
       4.0.10
        ```

    - How did you deploy DM: DM-Ansible or manually?

        ```
        DM-Ansible
        ```

    - Other interesting information (system version, hardware config, etc):

        >
        >

5. current status of DM cluster (execute `query-status` in dmctl)

6. Operation logs
   - Please upload `dm-worker.log` for every DM-worker instance if possible
   - Please upload `dm-master.log` if possible
   - Other interesting logs
   - Output of dmctl's commands with problems
   
7. Configuration of the cluster and the task
   - `dm-worker.toml` for every DM-worker instance if possible
   - `dm-master.toml` for DM-master if possible
   - task config, like `task.yaml` if possible
   - `inventory.ini` if deployed by DM-Ansible

8. Screenshot/exported-PDF of Grafana dashboard or metrics' graph in Prometheus for DM if possible

**Comment by lance6716** [comment]
By checking the log of DM-worker, we can see when worker started the task it's continued to process sync unit, and at `07/20 15:24:07` worker just synchronize the binlog around `07/20 11:26:00`, so the initial lag is high.

at through log we can see some problems that blocks the synchronization all the time, so the lag is getting higher.

AFAIK, this issue could be explained by known problems
