### ISSUE TITLE
One dm-worker too slow in 200 mysql upstream environment

### ISSUE THREAD

**Issue by XuJianxu** [pingcap/dm#1892]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.
200 upstream mysql, 200* dm worker, 3*dm master, 200K QPS+TPS in upstream.
Upgrade dm cluster from 2.0.1 to nightly。

2. What did you expect to see?
All dm-worker work as expect.

3. What did you see instead?
One dm-worker too slow. 
Only 3K/s in lastest 54min.  
![image](https://user-images.githubusercontent.com/23207893/126309487-d31e298a-2c8d-4a22-bc52-51e6ee73d150.png)
![image](https://user-images.githubusercontent.com/23207893/126309493-1ff3adb9-885d-4109-8a40-3ca28403cde3.png)
![image](https://user-images.githubusercontent.com/23207893/126309503-388f443e-94d0-4a53-851a-e69b16786fd0.png)

4. Versions of the cluster

    - DM version (run `dmctl -V` or `dm-worker -V` or `dm-master -V`):

        ```
        2.0.1
        ```

    - Upstream MySQL/MariaDB server version:

        ```
       mysql5.6/5.7
        ```

    - Downstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

        ```
        4.0.10
        ```

    - How did you deploy DM: DM-Ansible or manually?

        ```
        (leave DM-Ansible or manually here)
        ```

    - Other interesting information (system version, hardware config, etc):

        >
        >

5. current status of DM cluster (execute `query-status` in dmctl)

6. Operation logs
   - Please upload `dm-worker.log` for every DM-worker instance if possible
   - Please upload `dm-master.log` if possible
   - Other interesting logs
   - Output of dmctl's commands with problems
   
7. Configuration of the cluster and the task
   - `dm-worker.toml` for every DM-worker instance if possible
   - `dm-master.toml` for DM-master if possible
   - task config, like `task.yaml` if possible
   - `inventory.ini` if deployed by DM-Ansible

8. Screenshot/exported-PDF of Grafana dashboard or metrics' graph in Prometheus for DM if possible

**Comment by lance6716** [comment]
through the log, we can see many errors such as

1. write confict, TxnLockNotFound ... etc, which is caused by DM didn't know the same table structure of downstream so generated wrong WHERE clause of DELETE and UPDATE DML, which will interfere with other transaction
2. because of above error, the progress is blocked so upstream killed the connection of DM because socket timeout

due to above error, the task progress didn't get forward, so the lag is getting higher
