### ISSUE TITLE
Transaction execution latency  on Monitor is different with log

### ISSUE THREAD

**Issue by XuJianxu** [pingcap/dm#1896]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.
200 upstream mysql, 200* dm worker, 3*dm master, 200K QPS+TPS in upstream.
Upgrade dm cluster from 2.0.1 to nightly。

2. What did you expect to see?
Grafana will deisply the correct info.

3. What did you see instead?
Transaction execution latency  on Monitor is different with log
![image](https://user-images.githubusercontent.com/23207893/126319065-580fd6b3-ce38-41a8-acf5-be10ee4b1794.png)
![image](https://user-images.githubusercontent.com/23207893/126319097-6dce1e30-d9e3-42f6-9529-d7bb54de59c4.png)

4. Versions of the cluster

    - DM version (run `dmctl -V` or `dm-worker -V` or `dm-master -V`):

        ```
        nightly
        ```

    - Upstream MySQL/MariaDB server version:

        ```
       mysql5.6/5.7
        ```

    - Downstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

        ```
        4.0.10
        ```

    - How did you deploy DM: DM-Ansible or manually?

        ```
        DM-Ansible
        ```

    - Other interesting information (system version, hardware config, etc):

        >
        >

5. current status of DM cluster (execute `query-status` in dmctl)

6. Operation logs
   - Please upload `dm-worker.log` for every DM-worker instance if possible
   - Please upload `dm-master.log` if possible
   - Other interesting logs
   - Output of dmctl's commands with problems
   
7. Configuration of the cluster and the task
   - `dm-worker.toml` for every DM-worker instance if possible
   - `dm-master.toml` for DM-master if possible
   - task config, like `task.yaml` if possible
   - `inventory.ini` if deployed by DM-Ansible

8. Screenshot/exported-PDF of Grafana dashboard or metrics' graph in Prometheus for DM if possible

**Comment by lance6716** [comment]
https://github.com/pingcap/dm/blob/cafaf9e49c2e35a22473ae07eccbeb1a4af86fe9/syncer/metrics/metrics.go#L143

because we only allow the metric variable storing a maximum of 1.4 minute, so it can't display 21 minute as printed in log.

It's very rare that transactions run such slow, I think 1.4 minute is enough, will close this issue.
