### ISSUE TITLE
Need to improve the log while dm cluster upgrade,  change ERROR to WARNING.

### ISSUE THREAD

**Issue by XuJianxu** [pingcap/dm#1913]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.
200*mysql upstream, 100*mysql independent data source，100*mysql shard table.
 200*dm-worker。 upgrade dm 2.0.1 -> nightly

2. What did you expect to see?
Report a WARNING, remind the previous connection already killed.

3. What did you see instead?
Report an error.
[2021/07/23 18:38:02.273 +08:00] [ERROR] [streamer_controller.go:321] ["fail to kill last connection"] [task=dm-task1234] [unit="binlog replication"] ["connection ID"=101] [error="[code=10001:class=database:scope=not-set:level=high], Message: database drive      r error, RawCause: Error 1094: Unknown thread id: 101, Workaround: Please check the database connection and the database config in configuration file."]

4. Versions of the cluster

    - DM version (run `dmctl -V` or `dm-worker -V` or `dm-master -V`):

        ```
        nightly
        ```

    - Upstream MySQL/MariaDB server version:

        ```
        5.7/5.8 
        ```

    - Downstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

        ```
       4.0.10
        ```

    - How did you deploy DM: DM-Ansible or manually?

        ```
        DM-Ansible
        ```

    - Other interesting information (system version, hardware config, etc):

        >
        >

5. current status of DM cluster (execute `query-status` in dmctl)

6. Operation logs
   - Please upload `dm-worker.log` for every DM-worker instance if possible
   - Please upload `dm-master.log` if possible
   - Other interesting logs
   - Output of dmctl's commands with problems
   
7. Configuration of the cluster and the task
   - `dm-worker.toml` for every DM-worker instance if possible
   - `dm-master.toml` for DM-master if possible
   - task config, like `task.yaml` if possible
   - `inventory.ini` if deployed by DM-Ansible

8. Screenshot/exported-PDF of Grafana dashboard or metrics' graph in Prometheus for DM if possible

**Comment by lance6716** [comment]
"Unknown thread id: 101" should have been fixed by relay refactoring. We can reopen the issue in ticdc if this happened again
