### ISSUE TITLE
dm对阿里RDS mydumper执行不成功

### ISSUE THREAD

**Issue by xqwbx163** [pingcap/dm#193]
最近在服务器上部署 了tidb-dm工具，本打算把阿里RDS 数据库的数据同步到tidb,结果尝试了很多回，都不成功，提示 必须获取 super权限锁表。
查看了dm工具利用了mydumper ,mydumper必须锁表才可以，但实际上阿里的RDS不提供super权限，
不知道开发人员有没有方法解决这个问题？

**Comment by csuzhangxc** [comment]
@xqwbx163 You can ref the method used for Amazon Aurora in <https://pingcap.com/docs-cn/v3.0/how-to/migrate/from-aurora/#%E7%AC%AC-6-%E6%AD%A5-%E6%9F%A5%E8%AF%A2%E4%BB%BB%E5%8A%A1>

**Comment by xqwbx163** [comment]
@csuzhangxc 
执行报错啊
** (mydumper:30069): WARNING **: 11:06:37.949: Executing in no-locks mode, snapshot will notbe consistent
Segmentation fault

**Comment by csuzhangxc** [comment]
@xqwbx163 could you provide
1. the version of DM
2. the log about the _Segmentation fault_ (may in _dm-worker.log_ or a separate _xx_mydumper.log_)

**Comment by xqwbx163** [comment]
2019/07/03 22:25:55.610 subtask.go:258: [error] [subtask] shard_merge_item dm-unit Sync process error with type ExecSQL:
 Error 1292: invalid time format: '{2999 12 31 23 59 59 0}'
github.com/pingcap/errors.AddStack
        /go/pkg/mod/github.com/pingcap/errors@v0.11.4/errors.go:174
github.com/pingcap/errors.Trace
        /go/pkg/mod/github.com/pingcap/errors@v0.11.4/juju_adaptor.go:15
github.com/pingcap/dm/syncer.(*Conn).executeSQLJobImp
        /home/jenkins/workspace/build_dm_master/go/src/github.com/pingcap/dm/syncer/db.go:237
github.com/pingcap/dm/syncer.(*Conn).executeSQLJob
        /home/jenkins/workspace/build_dm_master/go/src/github.com/pingcap/dm/syncer/db.go:196
github.com/pingcap/dm/syncer.(*Syncer).sync.func3
        /home/jenkins/workspace/build_dm_master/go/src/github.com/pingcap/dm/syncer/syncer.go:808
github.com/pingcap/dm/syncer.(*Syncer).sync
        /home/jenkins/workspace/build_dm_master/go/src/github.com/pingcap/dm/syncer/syncer.go:893
github.com/pingcap/dm/syncer.(*Syncer).Run.func2
        /home/jenkins/workspace/build_dm_master/go/src/github.com/pingcap/dm/syncer/syncer.go:977
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1337

**Comment by csuzhangxc** [comment]
@xqwbx163 so have you solved the _Segmentation fault_ of mydumper?

Do upstream and downstream have the same _sql-mode_ and _table schema_?

**Comment by xqwbx163** [comment]
i solve   the Segmentation fault of mydumper and the problem--"Error 1292: invalid time format: '{2999 12 31 23 59 59 0}'"
thanks for you help
