### ISSUE TITLE
binlog pos not catch up with master after upstream master-slave switch

### ISSUE THREAD

**Issue by GMHDBJD** [pingcap/dm#1930]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.
upstream master-slave switch
2. What did you expect to see?
syncer catch up with master: true
3. What did you see instead?
syncer catch up with master: false
4. Versions of the cluster

    - DM version (run `dmctl -V` or `dm-worker -V` or `dm-master -V`):

        ```
        master
        ```

**Comment by lance6716** [comment]
can't reproduce, close it
