### ISSUE TITLE
add more linter or staticchecker

### ISSUE THREAD

**Issue by Ehco1996** [pingcap/dm#1945]
## Feature Request

**Is your feature request related to a problem? Please describe:**

We currently use `golang-ci-lint`, which does not check the following code
```go
func t() {
	ticker := time.NewTicker(time.Second)
	defer ticker.Stop()
	for {
		select {
		case <-ticker.C:
			f, _ := os.OpenFile("1.txt", os.O_RDWR, 0644)
			defer f.Close()
		}
	}
}
```

So maybe we should add more linters/checker to make the codebase more robust.
such as
* https://staticcheck.io/docs/checks
* https://github.com/go-critic/go-critic

**Describe the feature you'd like:**

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by lance6716** [comment]
we have enabled go-critic 🤔 
https://github.com/pingcap/dm/blob/ccddd7dd71019a07695ad0d208da29a1442816e1/.golangci.yml#L12

**Comment by Ehco1996** [comment]
Strangely enough it seems to be checking out again now ....

Close this issue for now and open it again if it reappears later
