### ISSUE TITLE
update job is twice the true value in Binlog Event QPS metrics.

### ISSUE THREAD

**Issue by GMHDBJD** [pingcap/dm#1965]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.
upstream: 1 insert, 1 update, 1 delete
2. What did you expect to see?
insert Binlog Event QPS metrics, insert: update: delete = 1:1:1
3. What did you see instead?
insert Binlog Event QPS metrics, insert: update: delete = 1:2:1
<img width="483" alt="WX20210806-145734@2x" src="https://user-images.githubusercontent.com/35025882/128469833-1179d89b-1678-44a8-8e8e-bf449e978fbc.png">
4. Root Case

We use [Observe(time.Since(ec.startTime).Seconds())](https://github.com/pingcap/dm/blob/b3a6fd17d6c81aadca48b0d5a90b366e56ccfa49/syncer/syncer.go#L2122) to calculate for update job, 
but since one update event has two values(old value and new value), the time for genUpdateSql is [as twice as other job](https://github.com/pingcap/dm/blob/master/syncer/dml.go#L124-L125).
5. Idea
We may turn the update job into one half or use another way to calculate binlog event qps

**Comment by GMHDBJD** [comment]
Not a bug

**Comment by lance6716** [comment]
> Not a bug

Why not a bug? do you mean the ratio is indeed 1:2:1?

**Comment by GMHDBJD** [comment]
I can't reproduce it.
