### ISSUE TITLE
dm配置文件tbl-name项正则如何匹配特定结尾字符串

### ISSUE THREAD

**Issue by alwaystest18** [pingcap/dm#197]
使用ptonline工具修改表结构的话会临时创建 `_(tablename)_old` 与 `_(tablename)_new` 【括号内为上游同步的表名】  两个临时表导致同步中断，我想通过修改 black-white-list 的 tbl-name 项来同步这种格式的表，但是 dm 配置文件的正则是贪婪匹配的，如果写成 `^_.*_old$` 这种，会匹配所有满足 `_.*` 格式的表名，所以想问下这种情况该如何设置？

**Comment by kennytm** [comment]
Hmm I don't understand. A normal table named like `_foo` will never match `^_.*_old$` since it doesn't end with `_old`. And it has nothing to do with greediness since the `^` and `$` already anchored where to match.

**Comment by amyangfei** [comment]
Have you configured `online-ddl-scheme: pt` in your task config file?
DM supports synchronizing upstream's online DDL change via either `pt-online-schema-change` or `gh-ost`, if and only if `online-ddl-scheme` is configured. The temporary tables created by `pt-osc` or `gh-ost` will be automatically ignored during synchronization, and you don't need to add any `black-white-list` configuration for these temporary tables.

**Comment by alwaystest18** [comment]
> Have you configured `online-ddl-scheme: pt` in your task config file?
> DM supports synchronizing upstream's online DDL change via either `pt-online-schema-change` or `gh-ost`, if and only if `online-ddl-scheme` is configured. The temporary tables created by `pt-osc` or `gh-ost` will be automatically ignored during synchronization, and you don't need to add any `black-white-list` configuration for these temporary tables.

@amyangfei I can't find any thing about "online-ddl-scheme: pt " at https://pingcap.com/docs-cn/
can you give me a link?

**Comment by amyangfei** [comment]
Oops  the `online-ddl-scheme` config is not included in the document, we will add it later.
you can refer to [source code reading about Online Schema Change](https://pingcap.com/blog-cn/dm-source-code-reading-8/) first

**Comment by csuzhangxc** [comment]
already added `online-ddl-scheme` config in https://pingcap.com/docs-cn/tidb-data-migration/stable/feature-online-ddl-scheme/.
