### ISSUE TITLE
Improve log readability when dmctl is used incorrectly

### ISSUE THREAD

**Issue by Ehco1996** [pingcap/dm#1988]
## Feature Request

**Is your feature request related to a problem? Please describe:**

`dmctl check-task --config ./tes.yaml`

When using dmctl with the above incorrect command, the current error message is easy to misinterpret

![image](https://user-images.githubusercontent.com/24697284/129170362-6cd10125-cec3-440f-a3fd-44a3aa9ed1a1.png)

**Describe the feature you'd like:**

Gives a more friendly hint, e.g. the current command parameter: `--config` is used incorrectly

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by lance6716** [comment]
what's the reason of this error, where is `:` 🤔

**Comment by Ehco1996** [comment]
> what's the reason of this error, where is `:` 🤔

wo need find and fix this 😬
