### ISSUE TITLE
The task cannot be transferred when dm-master leader and dm-worker down at the same time

### ISSUE THREAD

**Issue by Haaahei** [pingcap/dm#2002]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.
https://asktug.com/t/topic/123105

2. What did you expect to see?
the task cannot be transferred to new free dm-worker

3. What did you see instead?
the task should be transferred after new leader elected success

4. Versions of the cluster
DM v2.0.6 and lower

**Comment by lance6716** [comment]
hi, the worker has a keepalive TTL which is 1 minute (not enabled relay). so after 1 minute the source should be transferred to a free worker

**Comment by lance6716** [comment]
hi, the worker has a keepalive TTL which is 1 minute (not enabled relay). so after 1 minute the source should be transferred to a free worker

**Comment by Haaahei** [comment]
> hi, the worker has a keepalive TTL which is 1 minute (not enabled relay). so after 1 minute the source should be transferred to a free worker
> 
> https://docs.pingcap.com/zh/tidb-data-migration/stable/dm-worker-configuration-file#%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6%E7%A4%BA%E4%BE%8B

but not, we wait a long time, the task is not be transferred, you can found details from the log.

**Comment by Haaahei** [comment]
> hi, the worker has a keepalive TTL which is 1 minute (not enabled relay). so after 1 minute the source should be transferred to a free worker
> 
> https://docs.pingcap.com/zh/tidb-data-migration/stable/dm-worker-configuration-file#%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6%E7%A4%BA%E4%BE%8B

but not, we wait a long time, the task is not be transferred, you can found details from the log.

**Comment by lance6716** [comment]
Thanks for reporting, we are fixing this problem now!
