### ISSUE TITLE
the online-ddl-scheme value will be covered by online-ddl(false) after dm version upgrade to 2.0.6

### ISSUE THREAD

**Issue by Haaahei** [pingcap/dm#2034]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.
see https://asktug.com/t/topic/123401

2. What did you expect to see?
the value of online-ddl should not be default (false), should depend on the value of online-ddl-scheme

3. What did you see instead?
the value of online-ddl is false, this cause online-ddl-scheme not work.

**Comment by lance6716** [comment]
thanks for reporting, we will add an upgrading logic to adjust `online-ddl` in config in #2039 .
