### ISSUE TITLE
DM report  "tidb_enable_change_column_type is false" in dm-worker log

### ISSUE THREAD

**Issue by XuJianxu** [pingcap/dm#2066]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.
execute an incorrect ddl in upstream. 

2. What did you expect to see?
Report error, and no  "tidb_enable_change_column_type is false" mentioned.
tidb_enable_change_column_type is canceled.

3. What did you see instead?
[2021/08/30 17:29:16.122 +08:00] [ERROR] [subtask.go:308] ["unit process error"] [subtask=test] [unit=Sync] ["error information"="{\"ErrCode\":44006,\"ErrClass\":\"schema-tracker\",\"ErrScope\":\"internal\",\"ErrLevel\":\"high\",\"Message\":\"startLocation: [position: (binlog.000034, 6647), gtid-set: ], endLocation: [position: (binlog.000034, 6778), gtid-set: ], origin SQL: [alter table t2 change column e d  tinyint]: cannot track DDL: ALTER TABLE `list2`.`t2` CHANGE COLUMN `e` `d` TINYINT\",\"RawCause\":\"[ddl:8200]Unsupported modify column: length 4 is less than origin 20, and tidb_enable_change_column_type is false\"}"]

4. Versions of the cluster

    - DM version (run `dmctl -V` or `dm-worker -V` or `dm-master -V`):

        ```
       # ./dm-worker -V
            Release Version: v2.0.0-beta.2-377-ge120956c
            Git Commit Hash: e120956ce9ef240a06e291518d40243fc303e739
            Git Branch: master
            UTC Build Time: 2021-06-07 15:56:03
            Go Version: go version go1.16.4 linux/amd64
        ```

    - Upstream MySQL/MariaDB server version:

        ```
        mysql 5.7
        ```

    - Downstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

        ```
       nightly
        ```

    - How did you deploy DM: DM-Ansible or manually?

        ```
        DM-Ansible
        ```

    - Other interesting information (system version, hardware config, etc):

        >
        >

5. current status of DM cluster (execute `query-status` in dmctl)

6. Operation logs
   - Please upload `dm-worker.log` for every DM-worker instance if possible
   - Please upload `dm-master.log` if possible
   - Other interesting logs
   - Output of dmctl's commands with problems
   
7. Configuration of the cluster and the task
   - `dm-worker.toml` for every DM-worker instance if possible
   - `dm-master.toml` for DM-master if possible
   - task config, like `task.yaml` if possible
   - `inventory.ini` if deployed by DM-Ansible

8. Screenshot/exported-PDF of Grafana dashboard or metrics' graph in Prometheus for DM if possible

**Comment by XuJianxu** [comment]
It's probably a compatibility issue.

**Comment by lance6716** [comment]
see your DM version, it needs updating

**Comment by XuJianxu** [comment]
Verified in the 
# ./dm-worker -V
Release Version: v2.0.0-beta.2-486-ge008ef3e
Git Commit Hash: e008ef3e2d068da5c27e8df12700927d0f8719f7
Git Branch: master
UTC Build Time: 2021-08-27 08:36:14
Go Version: go version go1.16.4 linux/amd64

no error happened. 
Close this issue.
