### ISSUE TITLE
some columns will become NULL when upstream `binlog_row_image` is not `full`

### ISSUE THREAD

**Issue by lance6716** [pingcap/dm#2091]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

ref https://dev.mysql.com/doc/refman/8.0/en/replication-options-binary-log.html#sysvar_binlog_row_image

```sql
MySQL [test]> insert into t values (3,4);
Query OK, 1 row affected (0.007 sec)

MySQL [test]> update t set c = 30 where c = 3;
Query OK, 1 row affected (0.013 sec)
Rows matched: 1  Changed: 1  Warnings: 0

MySQL [test]> show session variables like 'binlog_row_image';
+------------------+---------+
| Variable_name    | Value   |
+------------------+---------+
| binlog_row_image | MINIMAL |
+------------------+---------+
1 row in set (0.003 sec)
```

2. What did you expect to see?

downstream

```sql
MySQL [test]> select * from t;
+----+------+
| c  | c2   |
+----+------+
| 10 |    2 |
| 30 |    4 |
+----+------+
```

3. What did you see instead?

downstream

```sql
MySQL [test]> select * from t;
+----+------+
| c  | c2   |
+----+------+
| 10 |    2 |
| 30 | NULL |
+----+------+
```

4. Versions of the cluster

    - DM version (run `dmctl -V` or `dm-worker -V` or `dm-master -V`):

        master

**Comment by lance6716** [comment]
for old data of UPDATE and DELETE only PK is written, so we lack the UK columns to correctly calculate causality in current row-level concurrency implementation. I'm going to simply add an error when found this case 😂

**Comment by lance6716** [comment]
found an user case https://asktug.com/t/topic/153305/4?u=lance6716

**Comment by Ehco1996** [comment]
> for old data of UPDATE and DELETE only PK is written, so we lack the UK columns to correctly calculate causality in current row-level concurrency implementation. I'm going to simply add an error when found this case 😂

What time to report this error?  i think we can report this error when we check config

**Comment by lance6716** [comment]
> > for old data of UPDATE and DELETE only PK is written, so we lack the UK columns to correctly calculate causality in current row-level concurrency implementation. I'm going to simply add an error when found this case 😂
> 
> What time to report this error? i think we can report this error when we check config

at runtime, because user can set session variable as example in issue description.

**Comment by sunzhaoyang** [comment]
1. check the `binlog_row_image` configuration before the task starts, it must be Full
2. binlog parsing process found in  non-Full format, error occurs and  the task paused
3. `ignore-checking-items`  changed to an implicit parameter,  remove from the online documentation and default configuration
@lance6716
