### ISSUE TITLE
Grafana display incorrect info for Running task Count 

### ISSUE THREAD

**Issue by XuJianxu** [pingcap/dm#2107]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.
Check the grafana status while  start 100 task in one dm-worker
2. What did you expect to see?
Grafana can display correct info 
3. What did you see instead?
Grafana display like below:
![image](https://user-images.githubusercontent.com/23207893/132472202-aab4ce65-7b9c-460a-a114-3125b2bceb9a.png)
![image](https://user-images.githubusercontent.com/23207893/132472225-29d01247-2804-4738-bf80-f06c922258b6.png)
 

4. Versions of the cluster

    - DM version (run `dmctl -V` or `dm-worker -V` or `dm-master -V`):

        ```
        nightly
        ```

    - Upstream MySQL/MariaDB server version:

        ```
        5.7
        ```

    - Downstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

        ```
        nignthly
        ```

    - How did you deploy DM: DM-Ansible or manually?

        ```
        DM-Ansible
        ```

    - Other interesting information (system version, hardware config, etc):

        >
        >

5. current status of DM cluster (execute `query-status` in dmctl)

6. Operation logs
   - Please upload `dm-worker.log` for every DM-worker instance if possible
   - Please upload `dm-master.log` if possible
   - Other interesting logs
   - Output of dmctl's commands with problems
   
7. Configuration of the cluster and the task
   - `dm-worker.toml` for every DM-worker instance if possible
   - `dm-master.toml` for DM-master if possible
   - task config, like `task.yaml` if possible
   - `inventory.ini` if deployed by DM-Ansible

8. Screenshot/exported-PDF of Grafana dashboard or metrics' graph in Prometheus for DM if possible

**Comment by kennytm** [comment]
the grafana board inside this repo is not a random-walk though 🤔 

https://github.com/pingcap/dm/blob/9e7b9ca5855ea338a4de6c24ec2d4648a1e858f5/dm/dm-ansible/scripts/DM-Monitor-Standard.json#L127-L137

**Comment by Ehco1996** [comment]
> the grafana board inside this repo is not a random-walk though 🤔
> 
> https://github.com/pingcap/dm/blob/9e7b9ca5855ea338a4de6c24ec2d4648a1e858f5/dm/dm-ansible/scripts/DM-Monitor-Standard.json#L127-L137

😂 fixed in https://github.com/pingcap/dm/pull/2113
