### ISSUE TITLE
dm支持MySQL到MySQL的全量+增量迁移吗？

### ISSUE THREAD

**Issue by wwwwwwchun** [pingcap/dm#213]
DM现在支持MySQL到MySQL的全量+增量迁移吗？就是源端和目标端都是MySQL数据库，主库MySQL开启了binlog但是未开启gtid，这样的场景支持吗？

**Comment by amyangfei** [comment]
DM is designed to satisfy TiDB, so some features in MySQL are not supported, such as foreign key, stored procedures and functions and so on. You can have more information from the official document [Compatibility with MySQL](https://pingcap.com/docs/dev/reference/mysql-compatibility/). All features that are compatible between TiDB and MySQL are supported in DM. 

If you want to use DM to synchronize data from MySQL to MySQL in a production environment, it is recommended to have a complete test. Besides it is very welcome to contribute code for features that are supported in MySQL but not supported by TiDB.
