### ISSUE TITLE
Where is meta data stored and how to restore a crash worker or task

### ISSUE THREAD

**Issue by whyliyu** [pingcap/dm#214]
We are considering using DM to sync mutiple mysql data into our tidb cluster, but I am worring about how to restore a task if it crashes by accident.

If meta data of a task is stored in a worker node, the task is difficult to restore if someting worng happens on this single node, such as disk broken.

It'd better to save meta data in a reliable place， but I didn't see any description about meta data.

Can anyone help clearify this?

**Comment by whyliyu** [comment]
Seems that meta data is saved in downstream tidb.
Accortding to https://pingcap.com/docs-cn/v3.0/reference/tools/data-migration/configure/task-configuration-file/

**Comment by amyangfei** [comment]
Synchronization status information, mainly checkpoint is stored in downstream TiDB, we can use this to restore a task.
Task information such as task running status, relay log and relay meta information is stored in local file system, if DM-worker process crashed, we can simply restart the DM-worker and it will automatically restore running tasks.
The worst case is accident happens on DM-worker nodes, such as disk damage or physical node unrecoverable broken, we have to re-seup DM-worker and synchronization manually, but we can still use the information from checkpoint to save time.

**Comment by whyliyu** [comment]
> Synchronization status information, mainly checkpoint is stored in downstream TiDB, we can use this to restore synchronization.
> Task information such as task running status, relay log and relay meta information is stored in local file system, if DM-worker process crashed, we can simply restart the DM-worker and it will automatically restore running tasks.
> The worst case is accident happens on DM-worker nodes, such as disk damage or physical node unrecoverable broken, we have to re-seup DM-worker and synchronization manually, but we can still use the information from checkpoint to save time.

Good answer， thanks
