### ISSUE TITLE
The URLs in "encountered incompatible DDL in TiDB" are dead

### ISSUE THREAD

**Issue by kennytm** [pingcap/dm#217]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

Run some incompatible DDLs. `query-status` will show an UnknownError containing this message:

https://github.com/pingcap/dm/blob/4abf188843fac4ccaac34c339179e59f2bfe4d3b/syncer/ddl.go#L32-L37

The two URLs listed here are dead and should be updated.

**Comment by amyangfei** [comment]
as a part of error message, I will update the docs dead link in https://github.com/pingcap/dm/pull/216

**Comment by amyangfei** [comment]
fixed in #216
