### ISSUE TITLE
mysql source worker %s has already started with source %s, but get a request with source %s

### ISSUE THREAD

**Issue by GMHDBJD** [pingcap/dm#2204]
### What did you do?

upgrade from v2.0.6 to v2.0.7
query-status

### What did you expect to see?

task runs normal

### What did you see instead?

```
error: mysql source worker %s has already started with source %s, but get a request with source %s
workaround: Please try restart this DM-worker
```

### Versions of the cluster

DM version (run `dmctl -V` or `dm-worker -V` or `dm-master -V`):
```console
v2.0.7
```

**Comment by lance6716** [comment]
as we discussed, since a "relay bound" worker should be treat as a free worker, I plan to add "relay" WorkerStage to (offline, free, bound). WorkerStage is not persisted so there should be no compatibility problem.
