### ISSUE TITLE
syncer does not support gtid yet

### ISSUE THREAD

**Issue by recall704** [pingcap/dm#241]
## Feature Request

when I use `RemoteBinlog` mode to sync data from mysql to mysql , I found that it doesn't support gtid yet

**Comment by GregoryIan** [comment]
@csuzhangxc would help it

**Comment by csuzhangxc** [comment]
@recall704 

you can add GTID support in [`generateStreamer`](https://github.com/pingcap/dm/blob/cb56783af3dfbee6682b6e45147078fe4bd5d5c5/syncer/syncer.go#L109) with [`BinlogSyncer.StartSyncGTID`](https://github.com/siddontang/go-mysql/blob/c884616485d64a28b4536e7aec5bbba0b4aed620/replication/binlogsyncer.go#L378).

if needed, you can ref `TCPReader` used by DM's relay unit in <https://github.com/pingcap/dm/blob/cb56783af3dfbee6682b6e45147078fe4bd5d5c5/pkg/binlog/reader/tcp.go#L87>.

**Comment by csuzhangxc** [comment]
supported in #521 (in DM 2.0).
