### ISSUE TITLE
Do DM support migrate data from mysql shards to 1 mysql?

### ISSUE THREAD

**Issue by louishust** [pingcap/dm#247]
## Question

From the docs, DM support migrate data from shard mysqls to tidb,
Do DM support migrate data from shard mysqls into 1 mysqll?

**Comment by csuzhangxc** [comment]
@louishust we use MySQL protocol to do the migration, but we have not verified if it works on MySQL carefully. 

BTW, some features like FOREIGN KEY are not supported by DM because we break the transaction in the upstream MySQL and execute DML statements concurrently into the downstream.

**Comment by louishust** [comment]
@csuzhangxc Thx for your reply
