### ISSUE TITLE
data race in unit test (syncer_test)

### ISSUE THREAD

**Issue by amyangfei** [pingcap/dm#248]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.
ref: https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/dm_ghpr_test/detail/dm_ghpr_test/1979/pipeline/53/

2. What did you expect to see?
ut runs successfully

3. What did you see instead?
data race

**Comment by amyangfei** [comment]
PTAL @3pointer

**Comment by csuzhangxc** [comment]
The content in CI has been purged, close it now and fix it ASAP if happened again.
