### ISSUE TITLE
DM support XA binlog event? ignore already executed gtid ?

### ISSUE THREAD

**Issue by louishust** [pingcap/dm#250]

**Comment by csuzhangxc** [comment]
@louishust 
1. DM does not support XA now and a near feature, and if the table which generating XA binlog event is not needed to be migrated you can filter it with [black-and-white-table-lists](https://pingcap.com/docs/v3.0/reference/tools/data-migration/features/overview/#black-and-white-table-lists)
2. Ignoring executed GTID may be supported in 2019, Q3

**Comment by louishust** [comment]
@csuzhangxc DM will report error or just ignore XA event ? And will dm support XA in future?

**Comment by csuzhangxc** [comment]
@louishust 
DM will report an error in the current version if no extra filter rules applied.

Whether XA is supported or not is still under investigation.

**Comment by sydnever** [comment]
@csuzhangxc  

Why save global checkpoint when handling XID event?

syncer.go

```go
func (s *Syncer) addJob(job *job) error {
	var (
		queueBucket int
		execDDLReq  *pb.ExecDDLRequest
	)
	switch job.tp {
	case xid:
		s.saveGlobalPoint(job.pos)
		return nil
```
