### ISSUE TITLE
update load unit with tidb-lightning's `tidb` backend

### ISSUE THREAD

**Issue by csuzhangxc** [pingcap/dm#282]
## Feature Request

**Is your feature request related to a problem? Please describe:**

tidb-lightning introduces a `tidb` `backend`, and it's robust than original load unit in DM.

**Describe the feature you'd like:**

update load unit with tidb-lightning's `tidb` backend

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by lance6716** [comment]
at least replaced by pingcap/tiflow#5833
