### ISSUE TITLE
上游mysql执行alter/rename table后，下游tidb同步中断，报data length too long

### ISSUE THREAD

**Issue by 331527583** [pingcap/dm#303]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.
上游mysql数据库执行的步骤：
a) create table A_alice 创建A表的新表（修改原始A表多处字段长度后的表，称为A_alice表）
b) insert into A_alice select * from A;
c) alter table A rename A.mid
d) alter table A_alice rename A; 新A表

2. What did you expect to see?
A_alice表插入A表数据，tidb-dm增量同步的数据，写入新A表（修改字段长度后）

3. What did you see instead?
tidb中：
A_alice只插入了一条记录；
tidb dm-worker报：
Error 1406: Data too long for column 'corp_name' at row 1 注：corp_name报错列，并没有修改过字段长度，实际是其他多处字段修改过长度。大量这类报错，都是在corp_name列报错，并且query-error超过grpc返回长度限制报错，覆盖了corp_name报错信息（rpc error: code = ResourceExhausted desc = grpc: received message larger than max (4247285 vs. 4194304)）

4. Versions of the cluster

    - DM version (run `dmctl -V` or `dm-worker -V` or `dm-master -V`):

        ```
        (paste DM version here, and you must ensure versions of dmctl, DM-worker and DM-master are same)
        ```
$ ./dmctl -V
Release Version: v1.0.0-alpha-46-g6855ea4
Git Commit Hash: 6855ea4e40bb5e3775709054a59a55c628a0922f
Git Branch: master
UTC Build Time: 2019-04-02 12:41:38
Go Version: go version go1.12 linux/amd64

$ ./dm-worker -V
Release Version: v1.0.0-alpha-46-g6855ea4
Git Commit Hash: 6855ea4e40bb5e3775709054a59a55c628a0922f
Git Branch: master
UTC Build Time: 2019-04-02 12:41:42
Go Version: go version go1.12 linux/amd64

$ ./dm-master -V
Release Version: v1.0.0-alpha-46-g6855ea4
Git Commit Hash: 6855ea4e40bb5e3775709054a59a55c628a0922f
Git Branch: master
UTC Build Time: 2019-04-02 12:41:48
Go Version: go version go1.12 linux/amd64
        ```
        (paste upstream MySQL/MariaDB server version here)
        ```

    - Downstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

        ```
        (paste TiDB cluster version here)
        ```
v2.1.4
    - How did you deploy DM: DM-Ansible or manually?

        ```
        (leave DM-Ansible or manually here)
        ```
DM-Ansible 

    - Other interesting information (system version, hardware config, etc):

        >Red Hat Enterprise Linux Server release 7.4 (Maipo)
        >上游mysql sql_mode：
STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
       > tidb sql_mode：
STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION
      > 

5. current status of DM cluster (execute `query-status` in dmctl)
    query-status没有保存，queryr-error大量报（如上）

6. Operation logs
   - Please upload `dm-worker.log` for every DM-worker instance if possible
   - Please upload `dm-master.log` if possible
   - Other interesting logs
   - Output of dmctl's commands with problems
   
7. Configuration of the cluster and the task
   - `dm-worker.toml` for every DM-worker instance if possible
   - `dm-master.toml` for DM-master if possible
   - task config, like `task.yaml` if possible
   - `inventory.ini` if deployed by DM-Ansible

8. Screenshot/exported-PDF of Grafana dashboard or metrics' graph in Prometheus for DM if possible

**Comment by 331527583** [comment]
恢复dm同步任务的方法：
1.drop tidb上A_alice表；
2.手动创建A_alice表；
3.resume-task 同步任务，
观察到：
A_alice表记录在同步；
alter table A rename A.mid 被执行
alter table A_alice rename A 被执行
A表增量同步在执行；
4.对比上游mysql和下游tidb的A表，数据记录相同

**Comment by csuzhangxc** [comment]
@331527583 can you upgrade DM to v1.0.1? ref:
1. https://pingcap.com/docs-cn/v3.0/reference/tools/data-migration/dm-upgrade/
2. https://pingcap.com/docs-cn/v3.0/reference/tools/download/#tidb-dm-data-migration

**Comment by 331527583** [comment]
谢谢，后续升级后，再观察下。
