### ISSUE TITLE
make build error 

### ISSUE THREAD

**Issue by stalary** [pingcap/dm#352]
## Question
I run `make build` in mac,
go: finding github.com/xiang90/probing latest
go: downloading github.com/xiang90/probing v0.0.0-20190116061207-43a291ad63a2
go: downloading github.com/ngaut/sync2 v0.0.0-20141008032647-7a24ed77b2ef
go: downloading sigs.k8s.io/yaml v1.1.0
go: downloading golang.org/x/tools v0.0.0-20191007185444-6536af71d98a
go: downloading golang.org/x/crypto v0.0.0-20191002192127-34f69633bfdc
go: downloading github.com/modern-go/reflect2 v1.0.1
go: downloading github.com/json-iterator/go v1.1.7
go: downloading github.com/modern-go/concurrent v0.0.0-20180306012644-bacd9c7ef1dd
go: downloading github.com/uber/jaeger-lib v2.0.0+incompatible
go: downloading github.com/dgrijalva/jwt-go v3.2.0+incompatible
bash: golint: command not found
make: *** [lint] Error 127

my go env

GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/mac/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/mac/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.11.5/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.11.5/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/mac/dm/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/16/7bjz9g2x5m9cm0bbbmfs0n4w0000gp/T/go-build264248443=/tmp/go-build -gno-record-gcc-switches -fno-common"

**Comment by csuzhangxc** [comment]
Is there any output about `golang.org/x/lint/golint`?

**Comment by stalary** [comment]
I copy my $GOPATH/src/golang.org/x/lint/golint/golint to dm resolve it, but I had a new problem.


gofmt(simplify)
GO111MODULE=off go get golang.org/x/lint/golint
golint
go: finding github.com/xiang90/probing latest
GO111MODULE=on go build -o bin/shadow golang.org/x/tools/go/analysis/passes/shadow/cmd/shadow
vet
go: finding github.com/xiang90/probing latest
go: downloading github.com/pingcap/check v0.0.0-20190102082844-67f458068fc8
go: downloading github.com/kami-zh/go-capturer v0.0.0-20171211120116-e492ea43421d
go: downloading github.com/DATA-DOG/go-sqlmock v1.3.3
go: finding github.com/xiang90/probing latest
# github.com/pingcap/dm/syncer [github.com/pingcap/dm/syncer.test]
syncer/checkpoint_test.go:300:15: undefined: strings.ReplaceAll
make: *** [vet] Error 2`

**Comment by csuzhangxc** [comment]
which version of Golang are you using?

**Comment by stalary** [comment]
> which version of Golang are you using?

1.11.5

**Comment by csuzhangxc** [comment]
1.12+ is needed.

**Comment by stalary** [comment]
> 1.12+ is needed.

Sorry, I'm going to upgrade now
