### ISSUE TITLE
remove mydumper dependence and use a Go implementation directly

### ISSUE THREAD

**Issue by siddontang** [pingcap/dm#395]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Now we must install mydumper explicitly to let DM to support full backup, it is not easy to operate.

why not let DM support dump directly?

**Describe the feature you'd like:**

Refer to https://github.com/xelabs/go-mydumper

Seem we can use the above Go lib directly, maybe the only risk is the stability of the lib. But the dump logic is easy, and I think we can hold the lib easily. 

**Describe alternatives you've considered:**
Maybe reinvent the wheel, it is not easy work. 

**Teachability, Documentation, Adoption, Migration Strategy:**
No

**Comment by kennytm** [comment]
Note that `go-mydumper` is GPL'ed so we can't use that project as a library. We could still bundle it as a separate executable and run it as a sub process but there won't be much advantage compared with the current mydumper in terms of integration.

**Comment by csuzhangxc** [comment]
already replaced with dumpling in #540.
