### ISSUE TITLE
Make binlog replication unit in DM can be compiled

### ISSUE THREAD

**Issue by WangXiangUSTC** [pingcap/dm#409]
## Overview

As we know, DM has four units, include dump、load、relay and binlog replication. The function of binlog replication is almost the same with [Syncer](https://pingcap.com/docs-cn/stable/reference/tools/syncer/), and is stronger than Syncer.

Some users use Syncer, and do some operations  development on Syncer on auto-failover and ddl compatibility. We can merge these code to DM, and make it stronger.

## Difficulty
Normal

## Score
2(develop)*3(days)*300(scores)

## TODO list
- [x] Make binlog replication unit be compiled

**Comment by GregoryIan** [comment]
@WangXiangUSTC please update the issue, like participant，latest progress,  and todo list

**Comment by WangXiangUSTC** [comment]
2019.12.11 talking with users, and identified the requirements. The biggest problem for users is DDL incompatibility and automatic error recovery. DM has been well supported, so we can continue to develop on DM. Make binlog replication unit be compiled.

**Comment by GregoryIan** [comment]
Good!  One thing need to note, some error recovery like `bad connection`, `invalid connection`,  are not handled in binlog replication unit of DM, but it seems not be a big problem, `Beike` has automated scripts do this
