### ISSUE TITLE
Is there a way to reload the dumped sql?

### ISSUE THREAD

**Issue by wanyaxing** [pingcap/dm#411]
## Question

Sometimes, I had dumped a huge data from mysql with server hours, then it's broken when there are errors in the sync task.

I want to clear the synced data and reload the sql form 0%.

Is there a way to do this? 

Thanks.

**Comment by csuzhangxc** [comment]
@wanyaxing For MySQL, there is no easy way to do this. For TiDB, you can dump tables one by one by set the same `tidb_snapshot` variable, or dump a single table with different `where_clause` and the same `tidb_snapshot` with our forked [Mydumper](https://pingcap.com/docs-cn/stable/reference/tools/mydumper/).

**Comment by wanyaxing** [comment]
> @wanyaxing For MySQL, there is no easy way to do this. For TiDB, you can dump tables one by one by set the same `tidb_snapshot` variable, or dump a single table with different `where_clause` and the same `tidb_snapshot` with our forked [Mydumper](https://pingcap.com/docs-cn/stable/reference/tools/mydumper/).

I can manually truncate all tables .

I want to reload this progress from 0% which I used dmctl.

![image](https://user-images.githubusercontent.com/7940795/70388197-61605900-19e9-11ea-88c7-28e869c47949.png)

Is there any command can be useful?

If not, I had to delete all dumped sql, and delete "xxxx_loader_checkpoint" in "dm_meta", and restart the task again, it will cost several hours again :(

**Comment by csuzhangxc** [comment]
Oh, you mean reloading (not dumping). That can be done by:
1. truncate all tables
2. set `offset` in all rows to `0` in "xxxx_loader_checkpoint" in "dm_meta".

**Comment by csuzhangxc** [comment]
BTW, you can ask questions in Chinese at https://asktug.com/.

**Comment by wanyaxing** [comment]
DM = mydumper + syncer

> Oh, you mean reloading (not dumping). That can be done by:
> 
> 1. truncate all tables
> 2. set `offset` in all rows to `0` in "xxxx_loader_checkpoint" in "dm_meta".

YES, GOT IT.

Thanks.
