### ISSUE TITLE
DM operator on K8S

### ISSUE THREAD

**Issue by IANTHEREAL** [pingcap/dm#43]
## Feature Request

**Describe the feature you'd like:**

Now we deploy and operate DM using Ansible, we have to do a lot of things manually.

For example, if you want to replicate binlog from a new MySQL instance, we should do：
1. [edit `Ansible inventory` and run an `ansible-playbook`](https://github.com/pingcap/docs/blob/master/tools/dm/cluster-operations.md#add-a-dm-worker-instance) to add a new dm-worker firstly；
2.  edit the task configuration file；
3.  if new task, start the task; otherwise you have to stop the task and the start the task

A vision - the user only operates the task configuration, maybe by web or a command line tool, and everything else is automated.

DM operator on K8S is a good choice

Project example: [TiDB-operator](https://github.com/pingcap/tidb-operator)

## Category

* Feature

## Value

K8s users can use DM more naturally.

## TODO list

N/A

## Documentations

N/A

## Project

N/A

**Comment by csuzhangxc** [comment]
some work have been done in #238, but may need to be refactored and refined.

**Comment by lance6716** [comment]
replaced by #238, close this
