### ISSUE TITLE
delete config `remove-meta` in task and add command to delete checkpoint info in dmctl

### ISSUE THREAD

**Issue by WangXiangUSTC** [pingcap/dm#448]
**Is your feature request related to a problem? Please describe:**

when user set `remote-meta` to `true`, `sync` and `load` unit will delete checkpoint information in init, if user restart dm-worker, the task will start with load again.

**Describe the feature you'd like:**

- delete config `remove-meta` in task
- add command to delete checkpoint info in dmctl

**Comment by csuzhangxc** [comment]
included in #567
