### ISSUE TITLE
Support from.password in command-line option

### ISSUE THREAD

**Issue by DanielZhangQD** [pingcap/dm#468]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Currently, users have to call dmctl to encrypt the password and set it in the config file, however, during integration with k8s and dbaas, sensitive info usually store in secret, which is more secure.
**Describe the feature you'd like:**

Add a command-line option for from.password, in this case, for k8s deployment, we can inject the password config to the dm-worker container and run dm-worker with that option.
**Describe alternatives you've considered:**

Or dm-worker can support retrieving the from.password from the environment variable.
**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by csuzhangxc** [comment]
we have removed `from` in DM-worker's config in DM HA.
