### ISSUE TITLE
English UI for DM portal

### ISSUE THREAD

**Issue by george24601** [pingcap/dm#475]
## Feature Request

**Is your feature request related to a problem? Please describe:**
DM portal is difficult to use for our non-Chinese engineers, since the portal is all in Chinese. 

**Describe the feature you'd like:**
English UI for DM portal

**Describe alternatives you've considered:**
N/A

**Teachability, Documentation, Adoption, Migration Strategy:**

Part of i18n

**Comment by csuzhangxc** [comment]
@baurine PTAL

**Comment by baurine** [comment]
Got, will add i18n support asap.

**Comment by WangXiangUSTC** [comment]
finished in https://github.com/pingcap/dm/pull/476
