### ISSUE TITLE
dm自己维护的checkpoint表内容需支持自定义

### ISSUE THREAD

**Issue by xiangfanglin** [pingcap/dm#478]
## Feature Request

**Is your feature request related to a problem? Please describe:**
如果启动了多个dm-syncer进行同步，dm-syncer自己维护的checkpoint表中的字段id的值均为默认值，没法区分是哪个dm-syncer的meta信息。如果dm-syncer同步出错，需手动修改binlog、pos点就无法进行修改，或启动多个dm-syncer同步到一个下游库可能导致有问题。

**Describe the feature you'd like:**
启动dm-syncer时，可通过配置或参数自定义该dm-syncer的id，在checkpoint表中用来区分是哪个dm-syncer维护的meta信息

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by WangXiangUSTC** [comment]
yes, we need add a configuration for dm-syncer's task name

**Comment by WangXiangUSTC** [comment]
fix in https://github.com/pingcap/dm/pull/482
