### ISSUE TITLE
reduce TiDB's log in dm-worker && etcd's log in dm-master

### ISSUE THREAD

**Issue by WangXiangUSTC** [pingcap/dm#495]
## Description

**Is your feature request related to a problem? Please describe:**

- In dm-worker, we use some code of tidb to execute DDL to keep the table's schema information and will output tidb's log in dm-worker's log file.

- In dm-master, we use etcd to save cluster's meta information and will output etcd's log in dm-master's log file.

The most of both etcd and tidb's log is useless and make logs too numerous.

**Describe the feature you'd like:**

Only print the error log of etcd and tidb, or output their log to another file.

## Score 

300

## Mentor(s)
* @csuzhangxc 

Contact the mentors: **#tidb-challenge-program** channel in [TiDB Community](https://join.slack.com/t/tidbcommunity/shared_invite/enQtNzc0MzI4ODExMDc4LWYwYmIzMjZkYzJiNDUxMmZlN2FiMGJkZjAyMzQ5NGU0NGY0NzI3NTYwMjAyNGQ1N2I2ZjAxNzc1OGUwYWM0NzE)  Slack Workspace

## Recommended Skills

* Golang
* Experience with DM

## Learning Materials

 * [The document for DM HA](https://docs.google.com/document/d/1zFCqZqxd5AgOsyIWGZ1fEPEuRMhKH7584tTNQ60l4Ig/edit#heading=h.h7g97d4262qg) in Chinese.

**Comment by GMHDBJD** [comment]
It seems that currently tidb's log from Mock TiKV is output to stdout . We can simply redirect it to another file using `> stdout.log 2>&1` when we start dm-worker. Should we add a config item for user and redirect stdout inside dm-worker?

We can simply set the log level for embed etcd. Should we add a config item for user to log it to another file?

**Comment by WangXiangUSTC** [comment]
I think we can simply set the log level, and it is not necessary to add a new config item for output log to stdout or dm-worker/dm-master's log.
