### ISSUE TITLE
UCP: remove `remove-meta` config for task

### ISSUE THREAD

**Issue by WangXiangUSTC** [pingcap/dm#496]
## Description

**Is your feature request related to a problem? Please describe:**

If set `remove-meta: true` in task's config file, it will always delete the meta information in the checkpoint table when starting/recovering the task. It is easy to misuse and delete the checkpoint, then the task will run as a new task.

**Describe the feature you'd like:**

- remove `remove-meta` config for task
- add another argument (like `--remove-meta`) for the `start-task` command
- or add a new command for dmctl to remove the meta information in checkpoint table, just like:
```
dmctl --master-addr "127.0.0.1:8261" --task-name test --remove-meta
```

## Score 

600

## Mentor(s)
* @csuzhangxc 

Contact the mentors: **#tidb-challenge-program** channel in [TiDB Community](https://join.slack.com/t/tidbcommunity/shared_invite/enQtNzc0MzI4ODExMDc4LWYwYmIzMjZkYzJiNDUxMmZlN2FiMGJkZjAyMzQ5NGU0NGY0NzI3NTYwMjAyNGQ1N2I2ZjAxNzc1OGUwYWM0NzE)  Slack Workspace

## Recommended Skills

* Golang
* Experience with DM

## Learning Materials

- [task configure](https://pingcap.com/docs-cn/stable/reference/tools/data-migration/configure/task-configuration-file-full/)
- [DM source reading](https://pingcap.com/blog-cn/#DM-%E6%BA%90%E7%A0%81%E9%98%85%E8%AF%BB)
- [DM document](https://pingcap.com/docs-cn/stable/reference/tools/data-migration/overview/#dm-%e6%9e%b6%e6%9e%84)

**Comment by csuzhangxc** [comment]
this has been done in #651.
