### ISSUE TITLE
HA: Add interface to query cluster information and status of DM-masters and DM-workers

### ISSUE THREAD

**Issue by lichunzhu** [pingcap/dm#500]
## Feature Request

**Is your feature request related to a problem? Please describe:**

It's hard for users to get DM clusters' status because the relationship of sources and workers are dynamic. The leader of DM will also change in some situations. Current `query-status` doesn't contain these information.
**Describe the feature you'd like:**

1. Add an interface in dm-master to query the DM-masters' and DM-workers' informations, roles and status.
2. Add cmd in dmctl to use this interface to get cluster information.

**Comment by csuzhangxc** [comment]
we have added `list-member` in #654.
