### ISSUE TITLE
support command to query relay's status in dmctl

### ISSUE THREAD

**Issue by WangXiangUSTC** [pingcap/dm#504]
## Description

**Is your feature request related to a problem? Please describe:**

Now we can only query relay's status by query task's status, if don't have any task, we don't have any command to query relay's status.

**Describe the feature you'd like:**

support a command to query relay's status, just like:
```
dmctl --master-addr "127.0.0.1:8261" --query-relay
```

## Score
1(developer) * 3(days) * 300(score) = 900

## Mentor(s)
* @csuzhangxc 

Contact the mentors: **#tidb-challenge-program** channel in [TiDB Community](https://join.slack.com/t/tidbcommunity/shared_invite/enQtNzc0MzI4ODExMDc4LWYwYmIzMjZkYzJiNDUxMmZlN2FiMGJkZjAyMzQ5NGU0NGY0NzI3NTYwMjAyNGQ1N2I2ZjAxNzc1OGUwYWM0NzE)  Slack Workspace

## Recommended Skills

* Golang
* Experience with DM

## Learning Materials

- [DM source reading](https://pingcap.com/blog-cn/#DM-%E6%BA%90%E7%A0%81%E9%98%85%E8%AF%BB)
- [DM document](https://pingcap.com/docs-cn/stable/reference/tools/data-migration/overview/#dm-%e6%9e%b6%e6%9e%84)

**Comment by lance6716** [comment]
Now we can using `query-status -s <source-id>` to get the relay status.
