### ISSUE TITLE
UCP: Support both encrypted and unencrypted passwords for the upstream and downstream database

### ISSUE THREAD

**Issue by csuzhangxc** [pingcap/dm#506]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Both encrypted and unencrypted passwords (by _dmctl_) are supported.

**Describe the feature you'd like:**

Support to pass both encrypted and unencrypted passwords (by _dmctl_) for the upstream and downstream database. 

## Score 

600

## Mentor(s)
* @csuzhangxc 

Contact the mentors: **#tidb-challenge-program** channel in [TiDB Community](https://join.slack.com/t/tidbcommunity/shared_invite/enQtNzc0MzI4ODExMDc4LWYwYmIzMjZkYzJiNDUxMmZlN2FiMGJkZjAyMzQ5NGU0NGY0NzI3NTYwMjAyNGQ1N2I2ZjAxNzc1OGUwYWM0NzE)  Slack Workspace

## Recommended Skills

* Golang
* Experience with DM

## Learning Materials

- [DM source reading](https://pingcap.com/blog-cn/#DM-%E6%BA%90%E7%A0%81%E9%98%85%E8%AF%BB)
- [DM document](https://pingcap.com/docs-cn/stable/reference/tools/data-migration/overview/#dm-%e6%9e%b6%e6%9e%84)

**Comment by Kuri-su** [comment]
Do i need to support like this?
```shell
$ dmctl --decrypt xxxxxxxxxxxxxxxxxxxxxxxxxxx
mypassword
```
but i don't know what's mean about "for the upstream and downstream database" in title :joy:

**Comment by csuzhangxc** [comment]
> Do i need to support like this?
> 
> ```shell
> $ dmctl --decrypt xxxxxxxxxxxxxxxxxxxxxxxxxxx
> mypassword
> ```
> 
> but i don't know what's mean about "for the upstream and downstream database" in title 😂

I mean, both encrypted or plaintext passwords are accepted in `source.toml` and `task.yaml`.

"upstream database" means passwords for the upstream/source MySQL instances, and "downstream database" means passwords for the downstream/target TiDB.

**Comment by Kuri-su** [comment]
> > Do i need to support like this?
> > ```shell
> > $ dmctl --decrypt xxxxxxxxxxxxxxxxxxxxxxxxxxx
> > mypassword
> > ```
> > 
> > 
> > but i don't know what's mean about "for the upstream and downstream database" in title joy
> 
> @Kuri-su I mean, both encrypted or plaintext passwords are accepted in `source.toml` and `task.yaml`.
> 
> "upstream database" means passwords for the upstream/source MySQL instances, and "downstream database" means passwords for the downstream/target TiDB.

ok, i got it.
