### ISSUE TITLE
HA: multiple sources create support in one command

### ISSUE THREAD

**Issue by csuzhangxc** [pingcap/dm#516]
## Feature Request

**Is your feature request related to a problem? Please describe:**

`operate-source create` can only create one source at a time now.

**Describe the feature you'd like:**

create multiple sources in one command.

**Describe alternatives you've considered:**

accept a directory path argument contain multiple source config files in one command.

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by lance6716** [comment]
we may support stop multiple sources for the same reason?

**Comment by csuzhangxc** [comment]
> we may support stop multiple sources for the same reason?

I think, YES.
