### ISSUE TITLE
HA: add and refactor metrics

### ISSUE THREAD

**Issue by csuzhangxc** [pingcap/dm#543]
## Feature Request

**Is your feature request related to a problem? Please describe:**

**Describe the feature you'd like:**

- add more metrics about HA, like metrics in DM-master.
- refactor previous metrics for HA (like updating `instance` to `source` for metrics in DM-worker).

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by lance6716** [comment]
part of new metrics[design]:
- number of workers in different state
- number of subtasks in different state by source
- number of operate errors increment (of different type?) by worker, so we could see worker should be scheduled out.

**Comment by lance6716** [comment]
part of new metrics:
- DDL errors will be reported in #790, but usage of these metrics is not very good
- going to report DDL number in un-synced/un-resolve states
