### ISSUE TITLE
DM supports automatic switching of upstream database

### ISSUE THREAD

**Issue by freemindLi** [pingcap/dm#550]
## Feature Request

**Is your feature request related to a problem? Please describe:**
Now, when the upstream database opens gtid, DM supports automatic switching to a new database and continues to synchronize from the last synchronized gtid point. However, if the upstream database does not open gtid, you need to record some information of the current upstream database and the information of the database to be cut, and set it in DM before you can start it Dynamic synchronization process: in the case of upstream database releasing failover, it is possible to switch automatically at any time, for example, the database may switch automatically, It is unrealistic，before the automatic switch, the relevant information of the upstream database is recorded, but if it is not recorded, the synchronized data will be confused, because the Binlong of the master and slave are not exactly the same
**Describe the feature you'd like:**
Perhaps, in the case where gtid is not enabled in the upstream database, DM also supports automatic switching of the upstream database. In the case of master slave, the position of binlog is inconsistent, but the time is consistent! So we can think like this: when the upstream database is switched, DM can push forward the current time (for example 60s, which can be set. The time for DM to switch the upstream database is relatively short in theory, and it is actually spent on the network).Therefore, in case of automatic switching, DM can search from the latest binlog to the binlog closest to the current time minus the backward time according to the configured backward time Position, and this point should be less than the current time minus the backward time. Furthermore, no matter whether we switch manually or the upstream database automatically, we don't need to record a bunch of information and do tedious operations, just set the backward time to complete the switch. Of course, these logics refer to otter!

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

## Category

* Usability

## Value

In the master-slave scenario, significantly reduce user operation and maintenance costs

## Documentations

N/A

## Project

N/A

**Comment by lance6716** [comment]
implemented in v2.0.2
