### ISSUE TITLE
Unexpected timezone for heartbeat ts field

### ISSUE THREAD

**Issue by amyangfei** [pingcap/dm#562]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

A problem from [ask tug topic/33136](https://asktug.com/t/topic/33136)

2. What did you expect to see?

ts value in heartbeat table has the same timezone as `DM-worker`

3. What did you see instead?

timezone shift

4. Versions of the cluster

 - TiDB: v3.0.11
 - DM v1.0.3

5. Suggestion

DM uses `UTC_TIMESTAMP` for heartbeat ts, which has a **literal value** in UTC.
A simple way is to add `loc=Local` in heartbeat DB DSN, and insert ts field with `NOW()`

**Comment by csuzhangxc** [comment]
heartbeat value is only used in DM internally, we will not fix this.
