### ISSUE TITLE
HA: some rows is not replicated in shard mode with sysbench

### ISSUE THREAD

**Issue by csuzhangxc** [pingcap/dm#565]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

   - use sysbench to generate for one of tables in the upstream
   - use DM to replicate these data in shard mode

2. What did you expect to see?

    replication works as normal.

3. What did you see instead?

   some data lost.

4. Versions of the cluster

    - DM version (run `dmctl -V` or `dm-worker -V` or `dm-master -V`):

        ```
        DM nightly before March 20.
        ```

**Comment by WangXiangUSTC** [comment]
fix in https://github.com/pingcap/dm/pull/572
