### ISSUE TITLE
HA: `*_new` generated by pt-osc replicated to the downstream

### ISSUE THREAD

**Issue by csuzhangxc** [pingcap/dm#566]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

   - set `online-ddl-scheme: "pt"` in task's config
   - do online DDL with pt-osc.

2. What did you expect to see?

   only the real table's data replicated to the downstream.

3. What did you see instead?

   `*_new` generated by pt also replicated to the downstream.

4. Versions of the cluster

    - DM version (run `dmctl -V` or `dm-worker -V` or `dm-master -V`):

        ```
        DM nightly before March 20.
        ```

**Comment by lichunzhu** [comment]
It's caused by a misuse of task.yaml.
