### ISSUE TITLE
do not auto resume for optimistic shard DDL conflict

### ISSUE THREAD

**Issue by csuzhangxc** [pingcap/dm#582]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

    run DDL in optimistic mode with conflict.

2. What did you expect to see?

    the subtask becomes paused.

3. What did you see instead?

    the subtask auto resume after paused.

4. Versions of the cluster

    - DM version (run `dmctl -V` or `dm-worker -V` or `dm-master -V`):

        ```
       DM nightly until April 8th.
        ```

**Comment by GMHDBJD** [comment]
Auto resume will also cause a bug in 1.0 and pessimistic mode in 2.0. When ddl conflict in different table but same database, it will cause [ErrSyncUnitDDLWrongSequence](https://github.com/pingcap/dm/blob/24b0be9b7c64250e1680558589db5826dfee2894/syncer/sharding-meta/shardmeta.go#L203) error. After auto resume, it will return [nil](https://github.com/pingcap/dm/blob/24b0be9b7c64250e1680558589db5826dfee2894/syncer/sharding-meta/shardmeta.go#L181) and doesn't check conflict. Then that database will always sync the last ddl in sharding group no mater the ddl is conflict or not.

**Comment by csuzhangxc** [comment]
> Auto resume will also cause a bug in 1.0 and pessimistic mode in 2.0. When ddl conflict in different table but same database, it will cause [ErrSyncUnitDDLWrongSequence](https://github.com/pingcap/dm/blob/24b0be9b7c64250e1680558589db5826dfee2894/syncer/sharding-meta/shardmeta.go#L203) error. After auto resume, it will return [nil](https://github.com/pingcap/dm/blob/24b0be9b7c64250e1680558589db5826dfee2894/syncer/sharding-meta/shardmeta.go#L181) and doesn't check conflict. Then that database will always sync the last ddl in sharding group no mater the ddl is conflict or not.

@GMHDBJD Is `resume-task` manually can still cause this bug?

**Comment by GMHDBJD** [comment]
> > Does`resume-task` manually still cause this bug?
The task auto resume after paused, and no need to resume-task. 🤔

**Comment by csuzhangxc** [comment]
> > Does`resume-task` manually still cause this bug?
> 
> The task auto resume after paused, and no need to resume-task. 🤔

If we disable auto resume, but the user `resume-task` manually, is this bug still exist?

**Comment by GMHDBJD** [comment]
Yes, still exist.
