### ISSUE TITLE
syncer: fail to handle `create database` query event in optimistic mode

### ISSUE THREAD

**Issue by WangXiangUSTC** [pingcap/dm#592]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

create shard task with optimistic mode, and then `create database sharding_target_opt`

2. What did you expect to see?

create database success

3. What did you see instead?

get error in dm-worker:

```
cannot fetch downstream table schema of `sharding_target_opt`.`` to initialize upstream schema `sharding_seq_opt`.`` in schema tracker`
```

4. Versions of the cluster

    - DM version (run `dmctl -V` or `dm-worker -V` or `dm-master -V`):
      master branch
      hash: be159edd7680b84377d8e88c42f9ea2b6aa715b0

**Comment by csuzhangxc** [comment]
fixed in #604.
