### ISSUE TITLE
dm-syncer support route-rules

### ISSUE THREAD

**Issue by WangXiangUSTC** [pingcap/dm#599]
## Feature Request

**Is your feature request related to a problem? Please describe:**

dm-syncer is a tools compiled from dm's syncer unit, and is used to replace syncer. issue: https://github.com/pingcap/dm/issues/409

dm-syncer already support config `route-rules`, but we have not to check whether this config can work.

**Describe the feature you'd like:**

1. add test case for `route-rules` in dm-syncer's integration test
2. if dm-syncer's `route-rules` can not work, need to fix it

## Score (Not for Hacktoberfest)

200

## Mentor(s)
* @csuzhangxc 

Contact the mentors: **#tidb-challenge-program** channel in [TiDB Community](https://join.slack.com/t/tidbcommunity/shared_invite/enQtNzc0MzI4ODExMDc4LWYwYmIzMjZkYzJiNDUxMmZlN2FiMGJkZjAyMzQ5NGU0NGY0NzI3NTYwMjAyNGQ1N2I2ZjAxNzc1OGUwYWM0NzE)  Slack Workspace

For Hacktoberfest: **#sig-migrate** in [TiDB Community](https://slack.tidb.io/invite?team=tidb-community&channel=sig-migrate&ref=github_sig) Slack Workspace

## Recommended Skills

* Golang
* Experience with DM

## Learning Materials

- [DM document](https://docs.pingcap.com/tidb-data-migration/stable/overview)
- [Syncer document](https://docs.pingcap.com/tidb/stable/syncer-overview)
- [DM-syncer's integration test](https://github.com/pingcap/dm/tree/master/tests/dm_syncer)

**Comment by csuzhangxc** [comment]
@Howie59 I'm sorry to inform you. UCP for usability improvement has been closed, so this issue can't be picked up now.
