### ISSUE TITLE
optimistic shard DDL do not support `ADD COLUMN` and `DROP COLUMN` in one statement well

### ISSUE THREAD

**Issue by csuzhangxc** [pingcap/dm#613]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

    execute one statement with both `ADD COLUMN` and `DROP COLUMN` in optimistic shard DDL mode

2. What did you expect to see?

    replication works normally.

3. What did you see instead?

    `ADD COLUMN` and `DROP COLUMN` replicated to the downstream directly, the DML from other tables can not replicated because miss column.

4. Versions of the cluster

    - DM version (run `dmctl -V` or `dm-worker -V` or `dm-master -V`):

        ```
        DM before git commit 5e3aaba3a1e9b186a3c13b00f8e7a0f472d177f0.
        ```

**Comment by csuzhangxc** [comment]
it will not be supported recently, instead to report an error in #656.

**Comment by lance6716** [comment]
maybe we should send split DDL and its TableInfo one-by-one

**Comment by lance6716** [comment]
closed by https://github.com/pingcap/dm/pull/1479
