### ISSUE TITLE
retry for errno.ErrWriteConflictInTiDB and errno.ErrWriteConflict

### ISSUE THREAD

**Issue by july2993** [pingcap/dm#619]
## Feature Request

**Is your feature request related to a problem? Please describe:**

once encounter errno.ErrWriteConflictInTiDB and errno.ErrWriteConflict the replication will abort
**Describe the feature you'd like:**

retry for errno.ErrWriteConflictInTiDB and errno.ErrWriteConflict
it 's safe to retry for dm.
**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by csuzhangxc** [comment]
fixed in https://github.com/pingcap/tidb-tools/pull/336 and https://github.com/pingcap/dm/pull/632
