### ISSUE TITLE
table checkpoint less than global checkpoint

### ISSUE THREAD

**Issue by dbtomato** [pingcap/dm#627]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

2. What did you expect to see?

3. What did you see instead?

4. Versions of the cluster

    - DM version (run `dmctl -V` or `dm-worker -V` or `dm-master -V`):
         Release Version: v1.0.4-hotfix

    - Upstream MySQL/MariaDB server version:

        ``` 
   percona 5.7.23
        ```

    - Downstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

        ```
       3.0.12
        ```

    - How did you deploy DM: DM-Ansible or manually?

        ```
       DM-Ansible
        ```

复制主库binlog，报错如下
anic error: table checkpoint (binlog|000001.017207, 913336818) less than global checkpoint (binlog|000001.017207, 1065558624)(flushed (binlog|000001.017207, 1065558624))\ngithub.com/pingcap/dm/pkg/terror.(*Error).
 
目前没有在asktug找到问题解答

**Comment by csuzhangxc** [comment]
有调整过 dm_meta 下的 checkpoint 表吗？
有更完整的 DM-worker 的 log 吗？

**Comment by lance6716** [comment]
closed by https://github.com/pingcap/dm/pull/1039
