### ISSUE TITLE
syncer: data race for `collectMetrics`

### ISSUE THREAD

**Issue by csuzhangxc** [pingcap/dm#637]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

    run CI

2. What did you expect to see?

    passed as normal.

3. What did you see instead?

    data race detected, see https://internal.pingcap.net/idc-jenkins/blue/rest/organizations/jenkins/pipelines/dm_ghpr_test/runs/4757/nodes/73/log/?start=0.

    this should be caused by https://github.com/pingcap/dm/issues/629.

4. Versions of the cluster

    - DM version (run `dmctl -V` or `dm-worker -V` or `dm-master -V`):

        ```
        https://github.com/pingcap/dm/pull/615
        ```

**Comment by WangXiangUSTC** [comment]
fix in https://github.com/pingcap/dm/pull/644
