### ISSUE TITLE
Refine dm-worker query-status prompt when failing from initialize task

### ISSUE THREAD

**Issue by lichunzhu** [pingcap/dm#657]
## Feature Request

**Is your feature request related to a problem? Please describe:**

When dm-worker starts a subtask but fail during the init, we will get `invalid_unit` but no error message from `query-status` command, which is a little bit confusing. 

**Describe the feature you'd like:**

https://github.com/pingcap/dm/pull/512 add result error to `query-error` command. cherry-pick this feature to `query-status` command will solve this problem.

**Comment by GMHDBJD** [comment]
Seems the error message has alreay been contained in [subtask.result](https://github.com/pingcap/dm/blob/ec66c436f99466bbc8bf72086185663661f77df0/dm/worker/status.go#L97) ?

**Comment by csuzhangxc** [comment]
> Seems the error message has alreay been contained in [subtask.result](https://github.com/pingcap/dm/blob/ec66c436f99466bbc8bf72086185663661f77df0/dm/worker/status.go#L97) ?

@GMHDBJD I think you are right and did your test cases in #736 also verified it?

**Comment by lichunzhu** [comment]
> Seems the error message has alreay been contained in [subtask.result](https://github.com/pingcap/dm/blob/ec66c436f99466bbc8bf72086185663661f77df0/dm/worker/status.go#L97) ?

sounds reasonable 🤔

**Comment by GMHDBJD** [comment]
> @GMHDBJD I think you are right and did your test cases in #736 also verified it?

Yes, I think we can close this issue.
