### ISSUE TITLE
dm cluster -- ansible-play start.yml get failed

### ISSUE THREAD

**Issue by loveleon** [pingcap/dm#67]
DM cluster information,blow:
dm cluster version:latest

When i run 'ansible-playbook start.yml' for start dm cluster.
i get below informations.
=====================================================================
PLAY [grafana_servers] ************************************************************************************************************************************************

TASK [start grafana by systemd] ***************************************************************************************************************************************
changed: [grafana]

TASK [wait for grafana up] ********************************************************************************************************************************************
ok: [grafana]

TASK [set_fact] *******************************************************************************************************************************************************
ok: [grafana]

TASK [import grafana data source] *************************************************************************************************************************************
changed: [grafana]

TASK [import grafana dashboards - prepare config] *********************************************************************************************************************
changed: [grafana -> localhost]

TASK [import grafana dashboards - run import script] ******************************************************************************************************************
fatal: [grafana -> localhost]: FAILED! => {"changed": true, "cmd": "python import_grafana_dashboards.py", "delta": "0:00:00.095492", "end": "2019-03-07 10:34:27.356195", "msg": "non-zero return code", "rc": 1, "start": "2019-03-07 10:34:27.260703", "stderr": "Traceback (most recent call last):\n  File \"import_grafana_dashboards.py\", line 95, in <module>\n    raise RuntimeError\nRuntimeError", "stderr_lines": ["Traceback (most recent call last):", "  File \"import_grafana_dashboards.py\", line 95, in <module>", "    raise RuntimeError", "RuntimeError"], "stdout": "[load] from <dm.json>:dm_worker\n[import] <Dm-Cluster-DM-worker> to [Dm-Cluster]\t............. ERROR:  [Errno 113] No route to host", "stdout_lines": ["[load] from <dm.json>:dm_worker", "[import] <Dm-Cluster-DM-worker> to [Dm-Cluster]\t............. ERROR:  [Errno 113] No route to host"]}
	to retry, use: --limit @/home/tidb/dm-ansible/retry_files/start.retry

PLAY RECAP ************************************************************************************************************************************************************
alertmanager               : ok=2    changed=1    unreachable=0    failed=0   
dm-worker1-1               : ok=2    changed=1    unreachable=0    failed=0   
dm-worker1-2               : ok=2    changed=1    unreachable=0    failed=0   
dm_master                  : ok=2    changed=1    unreachable=0    failed=0   
grafana                    : ok=5    changed=3    unreachable=0    failed=1   
localhost                  : ok=0    changed=0    unreachable=0    failed=0   
prometheus                 : ok=2    changed=1    unreachable=0    failed=0   

[tidb@mysql-15-100 dm-ansible]$ ls
===================================================================

From the error information,when do 'python import_grafana_dashboards.py' get "No route to host",this error let me puzzled.In my opinion,whether the dm.json file version is not correct with 'import_grafana_dashboards.py' version？Or  some other questions? TKS a lot for your help!

**Comment by amyangfei** [comment]
Have you configured grafana ip in `inventory.ini`?
```
[grafana_servers]
grafana ansible_host=<grafana ip>
```
If configured recheck whether you can access this ip from your server

**Comment by loveleon** [comment]
yes,i have done it. 
i have already get it fine.

**Comment by wfxxh** [comment]
How do you resolve this probleam? I have configured grafana ip in inventory.ini but this problem still arises
