### ISSUE TITLE
Possibly data race when starting several tasks on one worker

### ISSUE THREAD

**Issue by lichunzhu** [pingcap/dm#672]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.
Run serveral tasks at one time on a worker.

2. What did you expect to see?
Run normally.

3. What did you see instead?
Data race at collecting metrics.
![image](https://user-images.githubusercontent.com/21104942/82419603-3ce8cc80-9ab1-11ea-950c-a42095de56a8.png)
To fix this, we should move cpu usage metrics to worker server level but not unit level.
DM v1.0 and v2.0 both have this problem.

**Comment by GMHDBJD** [comment]
fix in #696
