### ISSUE TITLE
DM-master resign from leader when start scheduler is failed

### ISSUE THREAD

**Issue by lichunzhu** [pingcap/dm#674]
## Feature Request

**Is your feature request related to a problem? Please describe:**

When DM-master fails to start scheduler it will still serve as leader but will refuse scheduler related service. This resign should be retried several times.

**Describe the feature you'd like:**

Retire leader directly when election is failed.

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by csuzhangxc** [comment]
one case why we needed it below.

1. 5 DM-master members, kill 2 of them.
2. DM-master-3 became the leader
3. kill DM-master-3 
    1. DM-master-3 resign from the leader
    2. DM-master-4 became the leader
    3. embed etcd in DM-master-3 shutdown
    4. DM-master-4 can't bootstrap as a leader because only 2/5 etcd members alive now

**Comment by csuzhangxc** [comment]
done in #695.
