### ISSUE TITLE
Support setting session variables

### ISSUE THREAD

**Issue by csuzhangxc** [pingcap/dm#677]
## Feature Request

**Is your feature request related to a problem? Please describe:**

TiDB has some special variables, like [tidb_constraint_check_in_place](https://pingcap.com/docs-cn/stable/tidb-specific-system-variables/#tidb_constraint_check_in_place), and we may need to only set them for some sessions (or tasks).

NOTE: we can also use this to support set `SQL_MODE` for the session.

**Describe the feature you'd like:**

Support setting session variables

**Describe alternatives you've considered:**

add a new config item in `DBConfig` for session variables.

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by GMHDBJD** [comment]
support in #687
