### ISSUE TITLE
remove improper retry for `context.DeadlineExceeded` in syncer

### ISSUE THREAD

**Issue by csuzhangxc** [pingcap/dm#685]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

we have added retry for `context.DeadlineExceeded` with `continue`, no `needResync` + `reopenWithRetry` needed (https://github.com/pingcap/dm/blob/7b8154a15974cda8fde141e3d0bbed6e7f227922/syncer/syncer.go#L1210), and they are not proper.

If log a `reopen *syncer.localBinlogReader not supported`, this may let the user confuse.

**Comment by lance6716** [comment]
seems fixed by #716
