### ISSUE TITLE
DM同步报错DDLs

### ISSUE THREAD

**Issue by pingliuju** [pingcap/dm#686]
环境：
- 上游mysql：
 - mysql1：
   test_0库，其中包括分表及单表: test_0,test_1, temp
 - mysql2：
   test_1库，其中包括分表：test_0,test_1

- 下游tidb：
 test库，其中包括上游分表（合并成单表test），temp

- 现象：
在配置分表同步到下游库中，同步数据正常。但是在上游mysql1实例上执行单表temp的ddl语句
在查询同步任务状态时，会出现ddls锁（unsyncer mysql2实例未同步）
 "locks": [
        {
            "ID": "split-`test`.`temp`",
            "task": "split",
            "owner": "127.0.0.1:8237",
            "DDLs": [
                "ALTER TABLE `test`.`temp` ADD COLUMN `test_name` VARCHAR(10) DEFAULT NULL"
            ],
            "synced": [
                "10.254.0.34:8237"
            ],
            "unsynced": [
                "10.254.0.34:8238"

- 配置规则
mysql-instances:
-
  source-id: "mysql-replica-01"      
  route-rules: ["test-database-rules","test-table-rules"]
  mydumper-config-name: "global"
  loader-config-name: "global" 
  syncer-config-name: "global" 

-
  source-id: "mysql-replica-02"       
  route-rules: ["test-database-rules","test-table-rules"]
  mydumper-config-name: "global"
  loader-config-name: "global"
  syncer-config-name: "global" 

routes:
  test-database-rules:
    schema-pattern: "test_?"
    target-schema: "test"
  test-table-rules:
    schema-pattern: "test_?"
    table-pattern: "test_?"
    target-schema: "test"
    target-table: "test"

- 提问
 - 如何正确配置实例中包含分表和单表的同步配置
 - 如何解决上述ddls的问题

**Comment by csuzhangxc** [comment]
@pingliuju 推荐将单表和分表拆到不同的 task 里。另外 shard DDL 有很多限制，https://pingcap.com/docs-cn/tidb-data-migration/stable/feature-shard-merge/#%e4%bd%bf%e7%94%a8%e9%99%90%e5%88%b6

**Comment by pingliuju** [comment]
你好，收到回复。如果真对同一个库的单表和分表做task拆分。
是否在不同task文件中配置filter过滤和black-white-list白黑名单
有没有当前类型的配置模版可供参考

**Comment by csuzhangxc** [comment]
就是配置 black-white-list

**Comment by pingliuju** [comment]
就是分表的task配置
- black-white-list
  其中单表的黑名单

单表的task配置
- black-white-list
 其中分表的黑名单
互相过滤这种吗

**Comment by csuzhangxc** [comment]
是的。

或者你可以换成 白名单的写法

分表 task 配置

- black-white-list
    其中分表的白名单


单表 task 配置

- black-white-list
    其中单表的白名单

**Comment by pingliuju** [comment]
好的，感谢耐心解答，我先尝试一下
