### ISSUE TITLE
sql_mode=ANSI_QUOTE not working in version 2.0

### ISSUE THREAD

**Issue by GMHDBJD** [pingcap/dm#693]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.
sql_mode=ANSI_QUOTE not working in version 2.0 but  works fine in 1.0
see #687 and #692
2. What did you expect to see?
sql_mode=ANSI_QUOTE works fine in 2.0
3. What did you see instead?
when set sql_mode=ANSI_QUOTE in 2.0, syncer raise error: ErrSchemaTrackerCannotParseDownstreamTable
4. Versions of the cluster

    - DM version (run `dmctl -V` or `dm-worker -V` or `dm-master -V`):

        ```
        v2.0.0-beta.1-20-gfd03b9c-dev
        ```

    - Upstream MySQL/MariaDB server version:

        ```
        5.7.30
        ```

    - Downstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

        ```
        v4.0.0-beta.2-392-gb4f42abc3
        ```

**Comment by GMHDBJD** [comment]
The issues is causeed by https://github.com/pingcap/dm/blob/master/syncer/syncer.go#L584-L595
show create table in tidb returns
![Screenshot (30)](https://user-images.githubusercontent.com/35025882/83257094-3d3a4380-a1e6-11ea-81c7-423fe0c77998.png)
but rows.Scan converts it to
![Screenshot (32)](https://user-images.githubusercontent.com/35025882/83257267-9904cc80-a1e6-11ea-9d5f-6ebb2e8fd4b1.png)

**Comment by GMHDBJD** [comment]
this issue cause by https://github.com/pingcap/dm/blob/master/syncer/syncer.go#L584-L612.
If sql_mode="ANSI_QUOTE", show create table will return
![Screenshot (36)](https://user-images.githubusercontent.com/35025882/83261069-5abedb80-a1ed-11ea-8870-596b5566fb61.png)
but pingcap/parser can't parse this sql .

**Comment by csuzhangxc** [comment]
it seems both 1.0 and 2.0 are using `github.com/pingcap/parser v0.0.0-20200422082501-7329d80eaf2c`.

Is it caused by TiDB with mockTiKV in 2.0?

Can we resolve this by upgrade tidb & parser to a newer version? (or simply try it directly in a new tidb with mockTiKV)

**Comment by GMHDBJD** [comment]
set `enable-ansi-quotes: true` in task config solve this problem.
