### ISSUE TITLE
how can i config prometheus addr？

### ISSUE THREAD

**Issue by lddlww** [pingcap/dm#697]
question:
```
in dm master.toml or worker.toml

not find prometheus addr  and grafana addr config

```

**Comment by csuzhangxc** [comment]
@lddlww Prometheus can **pull** metrics from DM-worker's `worker-addr`, and DM-worker **doesn't push** metrics to Prometheus, so no Prometheus addr exists in worker.toml.

**Comment by lddlww** [comment]
@csuzhangxc thanks for replay

i am closing this issue
