### ISSUE TITLE
remove dumped data after load finished

### ISSUE THREAD

**Issue by csuzhangxc** [pingcap/dm#698]
## Feature Request

**Is your feature request related to a problem? Please describe:**

the dumped data was not removed even after all of them loaded successfully.

**Describe the feature you'd like:**

- remove dumped data automatically after loaded.
- add a new config item to keep the dumpled data if needed.

**Comment by lance6716** [comment]
I'm going to implement automatic deletion by periodically check whether `offset` in checkpoint equals to file size. Still learning code.
