### ISSUE TITLE
split drop multiple columns/partitions in one "alter table ... drop" clause

### ISSUE THREAD

**Issue by csuzhangxc** [pingcap/dm#699]
## Feature Request

**Describe the feature you'd like:**

support to split a statement like

```sql
ALTER TABLE tbl DROP PARTITION p1, p2;
```

**Comment by lance6716** [comment]
drop partition: tidb will support (prepare PR https://github.com/pingcap/tidb/pull/18419), maybe we could help

**Comment by lance6716** [comment]
drop multi-partition: https://github.com/pingcap/tidb/pull/18593

**Comment by lance6716** [comment]
drop multi-column is implemented in TiDB master, we may need to update tracker to catch up?

```
$ bin/tidb-server -V
Release Version: v4.0.0-beta.2-789-g871d00932
Edition: Community
Git Commit Hash: 871d00932c9f01b4ff39ce53aac4020634dd8b58
Git Branch: multi-part-drop
UTC Build Time: 2020-07-16 02:25:01
GoVersion: go1.13.6
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
```

**Comment by csuzhangxc** [comment]
> drop multi-column is implemented in TiDB master, we may need to update tracker to catch up?

@lance6716 you can update it (may also update the version of _parser_ and _pd_)

**Comment by lance6716** [comment]
> > drop multi-column is implemented in TiDB master, we may need to update tracker to catch up?
> 
> @lance6716 you can update it (may also update the version of _parser_ and _pd_)

OK, we'll update once after tidb#18593 is merged
