### ISSUE TITLE
split drop column with index

### ISSUE THREAD

**Issue by csuzhangxc** [pingcap/dm#700]
## Feature Request

**Is your feature request related to a problem? Please describe:**

TiDB can't drop a column with an index.

**Describe the feature you'd like:**

support to split `DROP COLUMN` with index

**Comment by lance6716** [comment]
same issue of TiDB SIG DDL https://github.com/pingcap/tidb/issues/3364

**Comment by lance6716** [comment]
to be clarify, we are expected to support drop index that only cover target column `c1`, such as `idx_1(c1)`, `idx_2(c1)` rather than `idx_3(c1, c2)`? or for `idx3` we drop joint index, drop column, create index for rest columns?
