### ISSUE TITLE
query-status can not throw any error，when no permission to access downstream db

### ISSUE THREAD

**Issue by lddlww** [pingcap/dm#708]
when  dm-worker no permission to access tidb；eg：
```
ERROR 1045 (28000): Access denied for user 'root'@'xxxxx' (using password:YES)
```
use query-status task：can not find any error， load progress always “0%”：
```
{
            "result": true,
            "worker": "10.5.2.1:8262",
            "msg": "",
            "subTaskStatus": [
                {
                    "name": "lancer",
                    "stage": "Running",
                    "unit": "Load",
                    "result": null,
                    "unresolvedDDLLockID": "",
                    "load": {
                        "finishedBytes": "0",
                        "totalBytes": "5290952158",
                        "progress": "0 %",
                        "metaBinlog": "(mysql-bin.000080, 811501527)"
                    }
                }
            ],
}

```

**Comment by csuzhangxc** [comment]
is there any log with "dispatch auto resume task" for DM-worker?

maybe the task is trying to auto-resume so looks as _running_.

**Comment by lddlww** [comment]
@csuzhangxc 
what's timeout for "auto-resume"？，or whether the task will always be auto-resume？

**Comment by csuzhangxc** [comment]
the timeout of "auto-resume" is a mechanism of backoff. the min value is 1s, the max value is 5min.

currently, we auto-resume for "Access denied for user" incorrectly.

**Comment by lddlww** [comment]
@csuzhangxc 
thanks，and i am closing this issue now
