### ISSUE TITLE
meaningless auto resume for "Error 1273: Unsupported collation when new collation is enabled: 'utf8_unicode_ci'"

### ISSUE THREAD

**Issue by csuzhangxc** [pingcap/dm#709]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

    run a data migration task.

2. What did you expect to see?

    the task keeps running and data are migrated.

3. What did you see instead?

    the task keeps _running_ but no data are migrated.

    in the log of DM, got 

    ```
    "Error 1273: Unsupported collation when new collation is enabled: 'utf8_unicode_ci'"
    ```

4. Versions of the cluster

    - DM version (run `dmctl -V` or `dm-worker -V` or `dm-master -V`):

        ```
        v2.0.0-beta.1
        ```

**Comment by djshow832** [comment]
TiDB doesn't support utf8_unicode_ci and will support it later, https://github.com/pingcap/tidb/issues/17596
For now, you can either do one of these:
1. Turn off new collation. That is, to use utf8_bin collation.
2. Keep the config untouched, change the collation of upstream to utf8_general_ci, it's similar to utf8_unicode_ci
