### ISSUE TITLE
Create tables in parallel in load unit

### ISSUE THREAD

**Issue by wjhuang2016** [pingcap/dm#717]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Currently, DM Sends the DDL request serially. If the TiDB is not the owner, it will take about 1s to deal with this request. For example, the create table statement is about to take 1s. But if the request is sent to the owner, it will take only 100ms.

**Describe the feature you'd like:**

DM can automatically send the ddl request to the owner.

**Describe alternatives you've considered:**

Send the del request concurrently, it's better, but still slower than to the owner directly.

**Teachability, Documentation, Adoption, Migration Strategy:**

No

## Score
- 600
## Mentor
- @lance6716

**Comment by csuzhangxc** [comment]
In fact, I don't think DM should do this special thing. and it may not work in many cases, like a proxy between DM and TiDB.

**Comment by wjhuang2016** [comment]
Now I want the alternative: Send the DDL request concurrently. It would be useful when the number of the database's table is large but the data is not much. @lance6716 PTAL.

**Comment by lance6716** [comment]
(only for full data migration phase) I think we could implement it after 2.0 GA. And lightning may also use concurrent create table? @kennytm @glorv @YuJuncen

**Comment by glorv** [comment]
Yes, if there are a lot of table, the performance of sending ddl tasks in parallel will be much better. 
There is a ticase of using lightning to restore 10k small tables, the current performance is quite slow.

**Comment by hidehalo** [comment]
Can I pick up this issue?

**Comment by lance6716** [comment]
> Can I pick up this issue?

added, please check again

**Comment by hidehalo** [comment]
> > Can I pick up this issue?
> 
> added, please check again

Thx!

/pick-up
