### ISSUE TITLE
resume task didn't check ddl conflict

### ISSUE THREAD

**Issue by GMHDBJD** [pingcap/dm#719]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.
`create database db`
`create table db.tb1 (id int)`
`create table db.tb2 (id int)`
`start-task`
`alter table db.tb1 add column a int`
`alter table db.tb2 add column b int`
2. What did you expect to see?
task will raise error when resume
3. What did you see instead?
when resume task, syncer will run the second ddl
4. Versions of the cluster

    - DM version (run `dmctl -V` or `dm-worker -V` or `dm-master -V`):

        ```
        1.0 and 2.0
        ```

**Comment by WangXiangUSTC** [comment]
what is the error message when resume? could you please add an example log.

**Comment by WangXiangUSTC** [comment]
> what is the error message when resume? could you please add an example log.

sorry, I made a mistake, ignore it

**Comment by csuzhangxc** [comment]
and another PR about this issue #741
