### ISSUE TITLE
Can it estimate replication lag based on the timestamp in the binlog event header

### ISSUE THREAD

**Issue by csuzhangxc** [pingcap/dm#728]
## Question

replication lag estimation similar with [Seconds_Behind_Master](https://dev.mysql.com/doc/refman/8.0/en/show-slave-status.html) to avoid _write_ permission for the upstream MySQL.

**Comment by csuzhangxc** [comment]
replication lag based on the timestamp may not work in cases:

- multiple replication level (MySQL-A -> MySQL-B -> DM)

**Comment by lance6716** [comment]
closed by https://github.com/pingcap/dm/pull/1709
