### ISSUE TITLE
use OPTIMISTIC mode default

### ISSUE THREAD

**Issue by 3pointer** [pingcap/dm#751]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Starting from v3.0.8, newly created TiDB clusters use the pessimistic transaction model by default
but for dm we can set session level optimistic transaction as default to improve performance. 

ref https://pingcap.com/docs/dev/pessimistic-transaction/
**Describe the feature you'd like:**

Add optimistic txn session config connect to TiDB

**Describe alternatives you've considered:**

And merge multiple statements into one statement with multiple values in one transaction would help to improve performance.
**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by csuzhangxc** [comment]
from DM v1.0.6, it supports to set session variables in `task.yaml`. 

but we may still change to use the optimistic transaction as default later.
