### ISSUE TITLE
sync-diff-inspector support check table by dm's task config

### ISSUE THREAD

**Issue by WangXiangUSTC** [pingcap/dm#767]
## Feature Request

sync-diff-inspector can get DM's task config file from DM-master, and then sync-diff-inspector generate diff task by DM's task config.

## Category

* Usability

## Value

Convenient for users to use diff.

## Value  Score

3

## User

N/A

**Comment by csuzhangxc** [comment]
get subtask config API added in #789, sync-diff-inspector is waiting to be updated.

**Comment by IANTHEREAL** [comment]
go ahead
