### ISSUE TITLE
improve quick start with dm docs

### ISSUE THREAD

**Issue by july2993** [pingcap/dm#781]
https://pingcap.com/docs-cn/tidb-data-migration/dev/quick-start-with-dm/

In 部署集群， it just make you start the process, and the "同步任务"  is totally unrelated to it.
e.g [准备数据](https://pingcap.com/docs-cn/tidb-data-migration/dev/quick-start-with-dm/#%E5%87%86%E5%A4%87%E6%95%B0%E6%8D%AE) this data is never used later, why make user prepare this.
you can not know how to use it flowing these docs.

**Comment by GMHDBJD** [comment]
I agree with you. We should change it.

**Comment by WangXiangUSTC** [comment]
fix in https://github.com/pingcap/docs-dm/pull/151

**Comment by july2993** [comment]
if use the data and task in https://pingcap.com/docs-cn/tidb-data-migration/dev/quick-start-create-task/

will meet:
```
root@control:/tiup-cluster# dmctl --master-addr n1:8261 start-task _dev/dm/task.yaml
{
    "result": false,
    "msg": "[code=26005:class=dm-master:scope=internal:level=medium], msg: 'fail to check synchronization configuration with type: check was failed, please see detail
    	detail: {
		"results": [
			{
				"id": 14,
				"name": "sharding table `db_target`.`t_target` consistency checking",
				"desc": "check consistency of sharding table structures",
				"state": "fail",
				"errorMsg": "instance mysql1 table `sharding1`.`t1` of sharding `db_target`.`t_target` have auto-increment key, would conflict with each other to cause data corruption",
				"instruction": "please handle it by yourself, read document https://pingcap.com/docs-cn/dev/reference/tools/data-migration/usage-scenarios/best-practice-dm-shard/#自增主键冲突处理 for more detail (only have Chinese document now, will translate to English later)",
				"extra": "auto-increment key checking"
			}
		],
		"summary": {
			"passed": false,
			"total": 15,
			"successful": 14,
			"failed": 1,
			"warning": 0
		}
	}', workaround: ''",
    "sources": [
    ]
}
```

suggest remove the `uid` and just make id as primary key int the prepare data part.

**Comment by csuzhangxc** [comment]
> auto-increment

fix again in https://github.com/pingcap/docs-dm/pull/235.
