### ISSUE TITLE
sql-skip not working

### ISSUE THREAD

**Issue by elvizlai** [pingcap/dm#795]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.
When using DM to migrate table and has error, try using `sql-skip` to fix but not work.

I had set mysql binlog type using `set global binlog_format=ROW;`

» `query-error test`
```
{
    "result": true,
    "msg": "",
    "workers": [
        {
            "result": true,
            "worker": "127.0.0.1:8262",
            "msg": "",
            "subTaskError": [
                {
                    "name": "test",
                    "stage": "Paused",
                    "unit": "Sync",
                    "sync": {
                        "errors": [
                        ]
                    }
                }
            ],
            "RelayError": {
                "msg": ""
            }
        }
    ]
}
```

» `query-status test`
```
{
    "result": true,
    "msg": "",
    "workers": [
        {
            "result": true,
            "worker": "127.0.0.1:8262",
            "msg": "",
            "subTaskStatus": [
                {
                    "name": "test",
                    "stage": "Paused",
                    "unit": "Sync",
                    "result": {
                        "isCanceled": false,
                        "errors": [
                            {
                                "Type": "UnknownError",
                                "msg": "",
                                "error": {
                                    "ErrCode": 36014,
                                    "ErrClass": 11,
                                    "ErrScope": 3,
                                    "ErrLevel": 3,
                                    "Message": "current pos (mysql-bin|000001.000010, 481670701): query update et_device_order_item t\n        set t.device_online_status = '20',\n        device_running_status = '掉线'\n        where t.device_raw_no = '123450001' and t.device_status = 20: only support ROW format binlog, unexpected DML statement found in query event",
                                    "RawCause": ""
                                }
                            }
                        ],
                        "detail": null
                    },
                    "unresolvedDDLLockID": "",
                    "sync": {
                        "totalEvents": "0",
                        "totalTps": "0",
                        "recentTps": "0",
                        "masterBinlog": "(mysql-bin.000010, 486800001)",
                        "masterBinlogGtid": "08e024dd-22db-11ea-837a-00163e04dda5:1-3918708",
                        "syncerBinlog": "(mysql-bin|000001.000010, 481670265)",
                        "syncerBinlogGtid": "",
                        "blockingDDLs": [
                        ],
                        "unresolvedGroups": [
                        ],
                        "synced": false
                    }
                }
            ],
            "relayStatus": {
                "masterBinlog": "(mysql-bin.000010, 486800001)",
                "masterBinlogGtid": "08e024dd-22db-11ea-837a-00163e04dda5:1-3918708",
                "relaySubDir": "0652de9c-ddd6-11e9-8f03-00163e00241b.000001",
                "relayBinlog": "(mysql-bin.000010, 486800001)",
                "relayBinlogGtid": "",
                "relayCatchUpMaster": true,
                "stage": "Running",
                "result": null
            },
            "sourceID": "mysql-replica-01"
        }
    ]
}
```

try using sql-skip to fix it
```
sql-skip -w 127.0.0.1:8262 --binlog-pos=mysql-bin|000001.000010:481670701 test
```

the related worker log
```
[2020/07/09 19:05:58.468 +08:00] [INFO] [server.go:346] [request=HandleSQLs] [payload="name:\"test\" binlogPos:\"mysql-bin|000001.000010:481670701\" "]
[2020/07/09 19:05:58.468 +08:00] [WARN] [operator.go:133] ["overwrite operator"] [task=test] [unit="binlog replication"] ["old operator"="uuid: 4644514c-90f3-43d2-8ea9-278bcfc58dd4, pos: (mysql-bin|000001.000010, 481670701), op: SKIP, args: "] ["new operator"="uuid: d7a1390f-fd9d-4fcf-be94-b1eaa11f312c, pos: (mysql-bin|000001.000010, 481670701), op: SKIP, args: "]
[2020/07/09 19:05:58.468 +08:00] [INFO] [operator.go:136] ["set a new operator"] [task=test] [unit="binlog replication"] ["new operator"="uuid: d7a1390f-fd9d-4fcf-be94-b1eaa11f312c, pos: (mysql-bin|000001.000010, 481670701), op: SKIP, args: "]
```

» `resume-task test`
```
{
    "op": "Resume",
    "result": true,
    "msg": "",
    "workers": [
        {
            "meta": {
                "result": true,
                "worker": "127.0.0.1:8262",
                "msg": ""
            },
            "op": "Resume",
            "logID": "27"
        }
    ]
}
```

2. What did you expect to see?
It should be work as expected.

3. What did you see instead?
Stage still `Paused`

4. Versions of the cluster

    - DM version (run `dmctl -V` or `dm-worker -V` or `dm-master -V`):

        ```
        Release Version: v1.0.6
        Git Commit Hash: eaf2683c05ab44143bfb286bfbbc3ba157c555cc
        Git Branch: release-1.0
        UTC Build Time: 2020-06-17 10:22:01
        Go Version: go version go1.13 linux/amd64
        ```

    - Upstream MySQL/MariaDB server version:

        ```
        5.7.17-log
        ```

    - Downstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

        ```
        Release Version: v4.0.2
        Edition: Community
        Git Commit Hash: 328b6d0a955c4668cf3188d02a6df42e16eaab4e
        Git Branch: heads/refs/tags/v4.0.2
        UTC Build Time: 2020-07-01 08:19:48
        GoVersion: go1.13
        Race Enabled: false
        TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
        Check Table Before Drop: false
        ```

    - How did you deploy DM: DM-Ansible or manually?

        ```
        (leave DM-Ansible or manually here)
        ```

    - Other interesting information (system version, hardware config, etc):

        >
        >

5. current status of DM cluster (execute `query-status` in dmctl)

6. Operation logs
   - Please upload `dm-worker.log` for every DM-worker instance if possible
   - Please upload `dm-master.log` if possible
   - Other interesting logs
   - Output of dmctl's commands with problems
   
7. Configuration of the cluster and the task
   - `dm-worker.toml` for every DM-worker instance if possible
   - `dm-master.toml` for DM-master if possible
   - task config, like `task.yaml` if possible
   - `inventory.ini` if deployed by DM-Ansible

8. Screenshot/exported-PDF of Grafana dashboard or metrics' graph in Prometheus for DM if possible

**Comment by GMHDBJD** [comment]
Can you please upload dm-worker.log and dm-master.log for more detail?

**Comment by elvizlai** [comment]
@GMHDBJD This is the error that mydump throw.

I tried using `./mydumper --tables-list abc-workorder.wo_workorder_schedule`
It turns out
```
** (mydumper:27463): CRITICAL **: 14:05:35.041: Error: DB: abc-workorder - Could not execute query: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-workorder LIKE 'wo_workorder_schedule'' at line 1
```

But using `./mydumper -B abc-workorder --tables-list wo_workorder_schedule` works.

**Comment by elvizlai** [comment]
@GMHDBJD I delete all dm_meta and rebuild dm(delete all logs files and generate file). This now show again.

**Comment by lance6716** [comment]
> @GMHDBJD This is the error that mydumper throw.
> 
> I tried using `./mydumper --tables-list abc-workorder.wo_workorder_schedule`
> It turns out
> 
> ```
> ** (mydumper:27463): CRITICAL **: 14:05:35.041: Error: DB: abc-workorder - Could not execute query: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-workorder LIKE 'wo_workorder_schedule'' at line 1
> ```
> 
> I compile the last version of [mydumper](https://github.com/maxbube/mydumper). It still now worked.
> 
> But using `./mydumper -B abc-workorder --tables-list wo_workorder_schedule` works.

same problem, replied here https://github.com/pingcap/dm/issues/796#issuecomment-656512493

**Comment by csuzhangxc** [comment]
`sql-skip` in DM v1.0 can't handle DMLs with STATEMENT binlog format (in QueryEvent), but in DM v2.0 you can use [`handle-error`](https://docs.pingcap.com/tidb-data-migration/v2.0/handle-failed-sql-statements#handle-error) to skip it.

if you have many DMLs with STATEMENT binlog format, it's better to use [`Block and allow table lists`](https://docs.pingcap.com/tidb-data-migration/v2.0/key-features#block-and-allow-table-lists) to filter the whole table
