### ISSUE TITLE
We have so many types of protobuf message!

### ISSUE THREAD

**Issue by lance6716** [pingcap/dm#811]
## Feature Request

**Is your feature request related to a problem? Please describe:**

I'm frustrated when adding automatic retry to leader-forward logic in every RPC method implementation, 
```
	isLeader, needForward := s.isLeaderAndNeedForward()
	if !isLeader {
		if needForward {
			return s.leaderClient.GetTaskCfg(ctx, req) // if failed because of leader switch, should retry imediately 
		}
		return nil, terror.ErrMasterRequestIsNotForwardToLeader
	}
```
because `req` has different type (`*pb.GetTaskCfgRequest`, `*pb.OperateSchemaRequest`...), and different type has different RPC (`GetTaskCfg`, `OperateSchema`) I found it's hard to bypass Go's type system for extracting some shared logic (logging, check leader-forward...)

**Describe the feature you'd like:**

change protobuf messages (XXXRequest, XXXResponse) to a unified message, for example,
```
message CommonResponse {
    string type = 1;
    string args = 2;
}
```
using unmarshal to decode `args` into structures in current messages, and `type` used by `switch` to dispatch different RPC method when finally called.

But we need edit more place when adding RPC, and keep `type` a valid type.

**Describe alternatives you've considered:**

use `interface{}`?

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by csuzhangxc** [comment]
@WangXiangUSTC @GMHDBJD PTAL and let's discuss it later?

**Comment by csuzhangxc** [comment]
just one notice, we still need to support HTTP API with grpc-gateway. 😢 

previously, we use [`callRPC`](https://github.com/pingcap/dm/blob/b145bf59315b84294cd9e5fd44188a6bc2b04287/dm/master/workerrpc/rawgrpc.go#L93) to handle call different methods for DM-worker.

**Comment by lance6716** [comment]
`callRPC` of worker RPC seems already have similar struct
```
type Request struct {
	Type CmdType

	StartSubTask   *pb.StartSubTaskRequest
	OperateSubTask *pb.OperateSubTaskRequest
        ...
}
```
so we could replace every mutually exclusive member to `CommonRequest`, and using `Type` (const int or string) to distinguish particular request type and dispatch method. 

for HTTP API, we might add some HTTP handler at `127.0.0.1:$MASTER_PORT/apis/v1alpha1` to convert to new message 😂. Also we could start a new version `apis/v2alpha1`, let two RPC both exist before test new RPC totally, then use convertor to replace. So much work to do 😂
