### ISSUE TITLE
Add a way to check the sources

### ISSUE THREAD

**Issue by july2993** [pingcap/dm#832]
## Feature Request

**Is your feature request related to a problem? Please describe:**

After adding some sources. ref https://pingcap.com/docs-cn/tidb-data-migration/dev/manage-source/#%E5%8A%A0%E8%BD%BD%E6%95%B0%E6%8D%AE%E6%BA%90%E9%85%8D%E7%BD%AE
```
root@control:/tiup-cluster# dmctl --master-addr n1:8261 operate-source create ./_dev/dm/source1.toml
{
    "result": true,
    "msg": "",
    "sources": [
        {
            "result": true,
            "msg": "",
            "source": "mysql1",
            "worker": "dm-172.19.0.104-8262"
        }
    ]
}
```
there's no way to check the sources?
how can I know what sources I have later? And check some issues like if some sources have no worker?

**Describe the feature you'd like:**

Add a way to check the sources

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by lance6716** [comment]
going to add `show-source` (or `operate-source show`, which is better?), to list added sources and its bounding worker.

BTW, similar to #398, we should re-orgnazation commands someday 😂, for example, support CRUD as second arguments for source/task/...

@csuzhangxc PTAL at your convenience

**Comment by csuzhangxc** [comment]
@lance6716 I think `operate-source show` is better.

> BTW, similar to #398, we should re-orgnazation commands someday 😂, for example, support CRUD as second argument for source/task/...

You are right! 😂
