### ISSUE TITLE
Exit code should not be 0 if failed to run command

### ISSUE THREAD

**Issue by july2993** [pingcap/dm#841]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.
```
root@control:/tiup-cluster/tests/tiup-dm/script/task# dmctl --master-addr n1:8261 operate-source create ./source1.tomldfdf
get file content error:
open ./source1.tomldfdf: no such file or directory
root@control:/tiup-cluster/tests/tiup-dm/script/task# echo $?
0
```
2. What did you expect to see?

exit code should not be 0

3. What did you see instead?

exit code is 0 which means the command run successfully.

4. Versions of the cluster

    - DM version (run `dmctl -V` or `dm-worker -V` or `dm-master -V`):

```
Release Version: v2.0.0-beta.2-6-gc8e0913
Git Commit Hash: c8e09137b049207adf136a2931a370727c9ba109
Git Branch: master
UTC Build Time: 2020-06-28 12:38:45
Go Version: go version go1.13 linux/amd64
```

**Comment by lance6716** [comment]
seems we should replace `Run` to `RunE` (with error) in `cobra.Command`
