### ISSUE TITLE
some args set in `mydumper` don't take effect

### ISSUE THREAD

**Issue by csuzhangxc** [pingcap/dm#862]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

   specify `statement-size` in `mydumper` config section.

2. What did you expect to see?

   `statement-size` takes effect.

3. What did you see instead?

   `statement-size` does not take effect, and can only be specified in `extra-args` to take effect.

4. Versions of the cluster

    - DM version (run `dmctl -V` or `dm-worker -V` or `dm-master -V`):

        ```
       v2.0.0-beta.2
        ```

**Comment by lichunzhu** [comment]
It sames serious... All configurations in `mydumper` won't take effect because they will be rewritten in https://github.com/pingcap/dm/blob/019f4995eec7a17cd95ee1dddf1b113b0436675f/dumpling/util.go#L49

**Comment by GMHDBJD** [comment]
I can't reproduce the bug. Both `statement-size` and `args: [--statement-size]` take effect. But if we set both, args will override the former one. I think it's a true behavior. 🤔

**Comment by GMHDBJD** [comment]
If we set other args, it will also override statement-size to 0. eg. args:[--chunk-filesize 64].
