### ISSUE TITLE
do not auto resume for "Error 1366" error

### ISSUE THREAD

**Issue by csuzhangxc** [pingcap/dm#921]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

2. What did you expect to see?

3. What did you see instead?

   `Incorrect datetime value: '466261494-02-09 03:09:21' for column 'c2' at row 1"`

    `[2020/08/24 15:33:20.353 +08:00] [INFO] [task_checker.go:350] ["dispatch auto resume task"] [component="task checker"] [task=task_single]`

4. Versions of the cluster

    - DM version (run `dmctl -V` or `dm-worker -V` or `dm-master -V`):

        ```
        v2.0.0-rc
        ```

**Comment by lance6716** [comment]
How could generate "Incorrect datetime value: '466261494-02-09 03:09:21' for column 'c2' at row 1" 🤔

**Comment by csuzhangxc** [comment]
😂  this value was generated by a MariaDB with a different time binary format with MySQL.

more error messages will exist for `Error 1366`, maybe you can use.

**Comment by lance6716** [comment]
can't imitate using newer MariaDB and `mysql56_temporal_format = OFF`. MariaDB 10.0 is hard to find a macOS/docker version 😢 can't manual test that PR

**Comment by csuzhangxc** [comment]
> MariaDB 10.0 is hard to find a macOS/docker version 😢 can't manual test that PR

I installed a Windows version last time... that's OK even lacking manual test.
