### ISSUE TITLE
The plaintext password is printed in the log

### ISSUE THREAD

**Issue by bqwzhl20** [pingcap/dm#94]
## Feature Request

**Is your feature request related to a problem? Please describe:**

in dm-worker.log, when mydumper exports data, the password is plaintext and should be coded using XXXXX

**Describe the feature you'd like:**

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by kennytm** [comment]
Thanks for the bug report. This issue has been fixed in #88 in the latest version.
