### ISSUE TITLE
correctly set etcdMember.ClientURLs

### ISSUE THREAD

**Issue by lance6716** [pingcap/dm#966]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

`list-member` shows etcdMember.ClientURLs, and use that to check if member was alive. This ClientURLs was generated using MasterAddr, which tends to set 0.0.0.0:port by Delivery team, so request to ClientURLs is in fact sent to local.

Set ClientURLs manually or to AdvertiseClientURLs (but can't use domain?)

by @lichunzhu 

4. Versions of the cluster

    - DM version (run `dmctl -V` or `dm-worker -V` or `dm-master -V`):

        current master

**Comment by lance6716** [comment]
maybe fixed by https://github.com/pingcap/dm/pull/955

**Comment by csuzhangxc** [comment]
maybe fixed by #820

**Comment by lichunzhu** [comment]
nightly version doesn't have this problem. Close this issue now.
