### ISSUE TITLE
Dm-master is abnormally closed when checking configuration files

### ISSUE THREAD

**Issue by hufangrui** [pingcap/dm#97]
![image](https://user-images.githubusercontent.com/13652255/55301806-f1b8c800-5470-11e9-805e-3f86e3970ccc.png)

![image](https://user-images.githubusercontent.com/13652255/55301740-a6061e80-5470-11e9-994b-d0a2720b45e8.png)

**Comment by csuzhangxc** [comment]
can you provide more information? at least:

1. DM version
2. you task config file (task.yaml)

**Comment by hufangrui** [comment]
Release Version: v1.0.0-alpha-41-ga6edf38
Git Commit Hash: a6edf38e174ff57bf8accd628b691d0c73a26ad3
Git Branch: master
UTC Build Time: 2019-03-27 11:04:10
Go Version: go version go1.12 linux/amd64


[task.txt](https://github.com/pingcap/dm/files/3027665/task.txt)

**Comment by csuzhangxc** [comment]
you must use an encrypted password for downstream (`target-database.password`) and upstream.
ref https://pingcap.com/docs/tools/dm/manage-task/#database-password-encryption

**Comment by hufangrui** [comment]
Thank you very much, Ignore the password encryption in the task configuration file.
